### ISSUE TITLE
numpy: ImportError: libtatlas.so.3: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by mw55309** [Linuxbrew/brew#119]
Here is the full error:

```
brew install homebrew/python/numpy
==> Installing numpy from homebrew/python
==> Using Homebrew-provided fortran compiler.
This may be changed by setting the FC environment variable.
==> Downloading https://files.pythonhosted.org/packages/e0/4c/515d7c4ac424ff38cc919f7099bf293dd064ba9a600e1e3835b3edefdb18/numpy-1.11.1.tar.gz
Already downloaded: /exports/cmvm/eddie/eb/groups/watson_grp/software/linuxbrew//.cache/Homebrew/numpy-1.11.1.tar.gz
==> Downloading https://pypi.python.org/packages/source/n/nose/nose-1.3.7.tar.gz
Already downloaded: /exports/cmvm/eddie/eb/groups/watson_grp/software/linuxbrew//.cache/Homebrew/numpy--nose-1.3.7.tar.gz
==> python -c import setuptools... --no-user-cfg install --prefix=/exports/cmvm/eddie/eb/groups/watson_grp/software/linuxbrew/.linuxbrew/Cellar/numpy/1.11.1/libexec/nose
==> python setup.py build --fcompiler=gnu95 --parallel=16 install --prefix=/exports/cmvm/eddie/eb/groups/watson_grp/software/linuxbrew/.linuxbrew/Cellar/numpy/1.11.1 --si
==> python -c import numpy; assert numpy.test().wasSuccessful()
Last 15 lines from /exports/cmvm/eddie/eb/groups/watson_grp/software/linuxbrew/.cache/Homebrew/Logs/numpy/03.python:
import numpy; assert numpy.test().wasSuccessful()

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/exports/cmvm/eddie/eb/groups/watson_grp/software/linuxbrew/.linuxbrew/Cellar/numpy/1.11.1/lib/python2.7/site-packages/numpy/__init__.py", line 180, in <module>
    from . import add_newdocs
  File "/exports/cmvm/eddie/eb/groups/watson_grp/software/linuxbrew/.linuxbrew/Cellar/numpy/1.11.1/lib/python2.7/site-packages/numpy/add_newdocs.py", line 13, in <module>
    from numpy.lib import add_newdoc
  File "/exports/cmvm/eddie/eb/groups/watson_grp/software/linuxbrew/.linuxbrew/Cellar/numpy/1.11.1/lib/python2.7/site-packages/numpy/lib/__init__.py", line 8, in <module>
    from .type_check import *
  File "/exports/cmvm/eddie/eb/groups/watson_grp/software/linuxbrew/.linuxbrew/Cellar/numpy/1.11.1/lib/python2.7/site-packages/numpy/lib/type_check.py", line 11, in <module>
    import numpy.core.numeric as _nx
  File "/exports/cmvm/eddie/eb/groups/watson_grp/software/linuxbrew/.linuxbrew/Cellar/numpy/1.11.1/lib/python2.7/site-packages/numpy/core/__init__.py", line 14, in <module>
    from . import multiarray
ImportError: libtatlas.so.3: cannot open shared object file: No such file or directory

READ THIS: https://github.com/Linuxbrew/brew/blob/master/share/doc/homebrew/Troubleshooting.md#troubleshooting
If reporting this issue please do so at (not Homebrew/brew):
  https://github.com/Homebrew/homebrew-python/issues

These open issues may also help:
problems installing Numpy https://github.com/Homebrew/homebrew-python/issues/333
Numpy HEAD builds require cython https://github.com/Homebrew/homebrew-python/issues/330
numpy: Add Cython as resource for --HEAD builds https://github.com/Homebrew/homebrew-python/pull/337
```

**Comment by sjackman** [comment]
Please report `brew gist-logs numpy`.

**Comment by mw55309** [comment]
I get:

```
Error: No logs.
```

When I try and re-run, I get a different error:

```
brew install homebrew/python/numpy
Cannot rebase: You have unstaged changes.
Please commit or stash them.
To restore the stashed changes to /exports/cmvm/eddie/eb/groups/watson_grp/software/linuxbrew/.linuxbrew run:
  'cd /exports/cmvm/eddie/eb/groups/watson_grp/software/linuxbrew/.linuxbrew && git stash pop'
==> Installing numpy from homebrew/python
==> Using Homebrew-provided fortran compiler.
This may be changed by setting the FC environment variable.
==> Downloading https://files.pythonhosted.org/packages/e0/4c/515d7c4ac424ff38cc919f7099bf293dd064ba9a600e1e3835b3edefdb18/numpy-1.11.1.tar.gz
######################################################################## 100.0%
(23) Failed writing body
Error: Failed to download resource "numpy"
Download failed: https://files.pythonhosted.org/packages/e0/4c/515d7c4ac424ff38cc919f7099bf293dd064ba9a600e1e3835b3edefdb18/numpy-1.11.1.tar.gz
```

**Comment by mw55309** [comment]
OK, completely removed linuxbrew, re-installed and numpy installed fine.

Gremlins.

**Comment by bw-yuhogg** [comment]
Glad to hear everything's working for you now!
