### ISSUE TITLE
python: in opensuse leap 42.1. no "-lcurses"

### ISSUE THREAD

**Issue by ccshao** [Linuxbrew/brew#125]
If Homebrew was updated on Aug 10-11th 2016 and `brew update` always says `Already up-to-date.` you need to run: `cd "$(brew --repo)" && git fetch && git reset --hard origin/master && brew update`.
# Please follow the general troubleshooting steps first:
- [X] Ran `brew update` and retried your prior step?
- [X] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [X] If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`?

_You can erase any parts of this template not applicable to your Issue._
### Bug reports:

could not install python with linux brew `brew install python`
I am using the opensuse leap 42.1. 
The error said: /usr/bin/ld: cannot find -lcurses
After googling, opensuse might use -lncurses instead of -lcurses, but I 
do not know how to change it in the make file from brew. 

`brew doctor` gave following warning:

```
Having additional scripts in your path can confuse software installed via
Homebrew if the config script overrides a system or Homebrew provided
script of the same name. We found the following "config" scripts:
    /usr/bin/X11/pkg-config
    /usr/bin/X11/x86_64-suse-linux-gnu-pkg-config
    /usr/bin/X11/brltty-config
    /usr/bin/X11/isolinux-config
    /usr/bin/X11/cups-config
    /usr/bin/X11/icu-config
    /usr/bin/X11/libart2-config
    /usr/bin/X11/ncurses5-config
    /usr/bin/X11/ncurses6-config
    /usr/bin/X11/ncursesw5-config
    /usr/bin/X11/ncursesw6-config
    /usr/bin/X11/python-config
    /usr/bin/X11/python2-config
    /usr/bin/X11/python2.7-config
    /usr/bin/X11/libpng16-config
    /usr/bin/X11/libpng-config
    /usr/bin/X11/freetype-config
    /usr/bin/X11/pcre-config
    /usr/bin/X11/curl-config
    /usr/bin/X11/xml2-config

Warning: Homebrew's share was not found in your XDG_DATA_DIRS but you have
this variable set to include other locations.
Some programs like `vapigen` may not work correctly.
Consider setting the XDG_DATA_DIRS for example like so
    echo 'export XDG_DATA_DIRS="/home/XXX/.linuxbrew/share:$XDG_DATA_DIRS"' >> ~/.bash_profile
```

**Comment by sjackman** [comment]
Please report the output of

``` sh
brew install python
brew gist-logs python
```

**Comment by ccshao** [comment]
@sjackman 

Today python is partially successfully installed, with a error 

> ImportError: /home/cshao/.linuxbrew/Cellar/python/2.7.12_1/lib64/python2.7/lib-dynload/_io.so: undefined symbol: PyUnicodeUCS2_Replace

**However,  pip is not installed**

`which pip` 
/usr/bin/pip

Full report of `brew install python`

```
==> Auto-updated Homebrew!
Updated 2 taps (homebrew/core, homebrew/science).
==> Updated Formulae
homebrew/science/mhap

==> Installing dependencies for python: readline, bzip2, homebrew/dupes/unzip, sqlite, gdbm, makedepend, openssl
==> Installing python dependency: readline
==> Downloading https://linuxbrew.bintray.com/bottles/readline-7.0.x86_64_linux.bottle.tar.gz
######################################################################## 100.0%
==> Pouring readline-7.0.x86_64_linux.bottle.tar.gz
🍺  /home/XXX/.linuxbrew/Cellar/readline/7.0: 46 files, 1.7M
==> Installing python dependency: bzip2
==> Downloading https://linuxbrew.bintray.com/bottles/bzip2-1.0.6_1.x86_64_linux.bottle.1.tar.gz
######################################################################## 100.0%
==> Pouring bzip2-1.0.6_1.x86_64_linux.bottle.1.tar.gz
🍺  /home/XXX/.linuxbrew/Cellar/bzip2/1.0.6_1: 29 files, 1.5M
==> Installing python dependency: homebrew/dupes/unzip
==> Downloading https://linuxbrew.bintray.com/bottles-dupes/unzip-6.0_2.x86_64_linux.bottle.tar.gz
######################################################################## 100.0%
==> Pouring unzip-6.0_2.x86_64_linux.bottle.tar.gz
🍺  /home/XXX/.linuxbrew/Cellar/unzip/6.0_2: 14 files, 416K
==> Installing python dependency: sqlite
==> Downloading https://sqlite.org/2016/sqlite-autoconf-3140200.tar.gz
######################################################################## 100.0%
==> ./configure --prefix=/home/XXX/.linuxbrew/Cellar/sqlite/3.14.2_1 --enable-dynamic-extensions
==> make install
🍺  /home/XXX/.linuxbrew/Cellar/sqlite/3.14.2_1: 13 files, 2.8M, built in 53 seconds
==> Installing python dependency: gdbm
==> Downloading https://linuxbrew.bintray.com/bottles/gdbm-1.12.x86_64_linux.bottle.tar.gz
######################################################################## 100.0%
==> Pouring gdbm-1.12.x86_64_linux.bottle.tar.gz
🍺  /home/XXX/.linuxbrew/Cellar/gdbm/1.12: 29 files, 687.4K
==> Installing python dependency: makedepend
==> Downloading https://linuxbrew.bintray.com/bottles/makedepend-1.0.5.x86_64_linux.bottle.1.tar.gz
######################################################################## 100.0%
==> Pouring makedepend-1.0.5.x86_64_linux.bottle.1.tar.gz
🍺  /home/XXX/.linuxbrew/Cellar/makedepend/1.0.5: 7 files, 76.6K
==> Installing python dependency: openssl
==> Downloading https://www.openssl.org/source/openssl-1.0.2j.tar.gz
######################################################################## 100.0%
==> perl ./Configure --prefix=/home/XXX/.linuxbrew/Cellar/openssl/1.0.2j --openssldir=/home/XXX/.linuxbrew/etc/openssl no-ssl2 zlib-dynamic shared ena
==> make depend
==> make
==> make test
==> make install MANDIR=/home/XXX/.linuxbrew/Cellar/openssl/1.0.2j/share/man MANSUFFIX=ssl
==> Downloading https://curl.haxx.se/ca/cacert-2016-04-20.pem
######################################################################## 100.0%
==> Caveats
A CA file has been bootstrapped using certificates from the system
keychain. To add additional certificates, place .pem files in
  /home/XXX/.linuxbrew/etc/openssl/certs

and run
  /home/XXX/.linuxbrew/opt/openssl/bin/c_rehash

==> Summary
🍺  /home/XXX/.linuxbrew/Cellar/openssl/1.0.2j: 1,703 files, 14.5M, built in 3 minutes 50 seconds
==> Installing python
==> Downloading https://www.python.org/ftp/python/2.7.12/Python-2.7.12.tar.xz
######################################################################## 100.0%
==> Downloading https://bugs.python.org/file30805/issue10910-workaround.txt
######################################################################## 100.0%
==> Patching
==> Applying issue10910-workaround.txt
patching file Include/pyport.h
Hunk #1 succeeded at 713 (offset 14 lines).
Hunk #2 succeeded at 736 (offset 14 lines).
==> ./configure --prefix=/home/XXX/.linuxbrew/Cellar/python/2.7.12_1 --enable-ipv6 --datarootdir=/home/XXX/.linuxbrew/Cellar/python/2.7.12_1/share --d
==> make
==> make install PYTHONAPPSDIR=/home/XXX/.linuxbrew/Cellar/python/2.7.12_1
==> Downloading https://files.pythonhosted.org/packages/9f/7c/0a33c528164f1b7ff8cf0684cf88c2e733c8ae0119ceca4a3955c7fc059d/setuptools-23.1.0.tar.gz
######################################################################## 100.0%
==> Downloading https://files.pythonhosted.org/packages/e7/a8/7556133689add8d1a54c0b14aeff0acb03c64707ce100ecd53934da1aa13/pip-8.1.2.tar.gz
######################################################################## 100.0%
==> Downloading https://files.pythonhosted.org/packages/c9/1d/bd19e691fd4cfe908c76c429fe6e4436c9e83583c4414b54f6c85471954a/wheel-0.29.0.tar.gz
######################################################################## 100.0%
==> /home/XXX/.linuxbrew/Cellar/python/2.7.12_1/bin/python -s setup.py --no-user-cfg install --force --verbose --single-version-externally-managed --rec
Last 15 lines from /home/XXX/.cache/Homebrew/Logs/python/post_install.01.python:
--no-user-cfg
install
--force
--verbose
--single-version-externally-managed
--record=installed.txt
--install-scripts=/home/XXX/.linuxbrew/Cellar/python/2.7.12_1/bin
--install-lib=/home/XXX/.linuxbrew/lib/python2.7/site-packages

Traceback (most recent call last):
  File "setup.py", line 6, in <module>
    import io
  File "/home/XXX/.linuxbrew/lib64/python2.7/io.py", line 51, in <module>
    import _io
ImportError: /home/XXX/.linuxbrew/Cellar/python/2.7.12_1/lib64/python2.7/lib-dynload/_io.so: undefined symbol: PyUnicodeUCS2_Replace
Warning: The post-install step did not complete successfully
You can try again using `brew postinstall python`
==> Caveats
Pip and setuptools have been installed. To update them
  pip install --upgrade pip setuptools

You can install Python packages with
  pip install <package>

They will install into the site-package directory
  /home/XXX/.linuxbrew/lib/python2.7/site-packages

See: https://github.com/Homebrew/brew/blob/master/docs/Homebrew-and-Python.md

==> Summary
🍺  /home/XXX/.linuxbrew/Cellar/python/2.7.12_1: 5,045 files, 97.5M, built in 1 minute 45 seconds
[XXX@a240-pc100 ~]$ brew update
Updated 1 tap (homebrew/core).
No changes to formulae.
```

`brew gist-logs python`
https://gist.github.com/anonymous/a21deca0f6a4dce261019a1b65901615

**Comment by sjackman** [comment]
I'd recommend installing Linuxbrew in `/home/linuxbrew/.linuxbrew` and using the precompiled binary bottle of `python`.

Alternatively…
`ImportError: /home/XXX/.linuxbrew/Cellar/python/2.7.12_1/lib64/python2.7/lib-dynload/_io.so: undefined symbol: PyUnicodeUCS2_Replace`
It looks to me as though libraries are getting confused between your hosts operating system's version of Python and Linuxbrew's version of Python. If it's an option for you, you may want to try removing the OpenSUSE python package.

**Comment by ccshao** [comment]
Thanks!

**Comment by sjackman** [comment]
Did using the bottle work for you?

**Comment by ccshao** [comment]
I didnt tried it yet. For now I uninstall the python of brew and stick to the stock python. 
I might try it few days later.

-- update

I uninstalled the pip of python3, re-install python. It still doesnt work. I will keep the stock python version.
