### ISSUE TITLE
brew install homebrew/fuse/ntfs-3g fails 

### ISSUE THREAD

**Issue by lixuenan** [Linuxbrew/brew#144]
```
==> Installing ntfs-3g from homebrew/fuse
Error: wrong number of arguments (0 for 1..3)
Please report this bug:
  https://github.com/Linuxbrew/brew/blob/master/docs/Troubleshooting.md#troubleshooting
/state/partition1/home/lixn/.linuxbrew/Library/Homebrew/requirement.rb:57:in `instance_eval'
/state/partition1/home/lixn/.linuxbrew/Library/Homebrew/requirement.rb:57:in `block in satisfied?'
/state/partition1/home/lixn/.linuxbrew/Library/Homebrew/requirement.rb:184:in `block in yielder'
/state/partition1/home/lixn/.linuxbrew/Library/Homebrew/extend/ENV.rb:25:in `with_build_environment'
/state/partition1/home/lixn/.linuxbrew/Library/Homebrew/requirement.rb:184:in `yielder'
/state/partition1/home/lixn/.linuxbrew/Library/Homebrew/requirement.rb:57:in `satisfied?'
/state/partition1/home/lixn/.linuxbrew/Library/Homebrew/formula_installer.rb:373:in `block in expand_requirements'
/state/partition1/home/lixn/.linuxbrew/Library/Homebrew/requirement.rb:216:in `block in prune?'
/state/partition1/home/lixn/.linuxbrew/Library/Homebrew/requirement.rb:214:in `catch'
/state/partition1/home/lixn/.linuxbrew/Library/Homebrew/requirement.rb:214:in `prune?'
/state/partition1/home/lixn/.linuxbrew/Library/Homebrew/requirement.rb:205:in `block (2 levels) in expand'
/state/partition1/home/lixn/.linuxbrew/Library/Homebrew/vendor/portable-ruby/2.0.0-p648/lib/ruby/2.0.0/set.rb:232:in `each_key'
/state/partition1/home/lixn/.linuxbrew/Library/Homebrew/vendor/portable-ruby/2.0.0-p648/lib/ruby/2.0.0/set.rb:232:in `each'
/state/partition1/home/lixn/.linuxbrew/Library/Homebrew/dependencies.rb:68:in `each'
/state/partition1/home/lixn/.linuxbrew/Library/Homebrew/requirement.rb:204:in `block in expand'
/state/partition1/home/lixn/.linuxbrew/Library/Homebrew/requirement.rb:203:in `each'
/state/partition1/home/lixn/.linuxbrew/Library/Homebrew/requirement.rb:203:in `expand'
/state/partition1/home/lixn/.linuxbrew/Library/Homebrew/formula.rb:1455:in `recursive_requirements'
/state/partition1/home/lixn/.linuxbrew/Library/Homebrew/formula_installer.rb:361:in `expand_requirements'
/state/partition1/home/lixn/.linuxbrew/Library/Homebrew/formula_installer.rb:310:in `compute_dependencies'
/state/partition1/home/lixn/.linuxbrew/Library/Homebrew/formula_installer.rb:135:in `verify_deps_exist'
/state/partition1/home/lixn/.linuxbrew/Library/Homebrew/formula_installer.rb:128:in `prelude'
/state/partition1/home/lixn/.linuxbrew/Library/Homebrew/cmd/install.rb:296:in `install_formula'
/state/partition1/home/lixn/.linuxbrew/Library/Homebrew/cmd/install.rb:160:in `block in install'
/state/partition1/home/lixn/.linuxbrew/Library/Homebrew/cmd/install.rb:160:in `each'
/state/partition1/home/lixn/.linuxbrew/Library/Homebrew/cmd/install.rb:160:in `install'
/state/partition1/home/lixn/.linuxbrew/Library/Homebrew/brew.rb:94:in `<main>'
```

How can I deal with this error ?

**Comment by sjackman** [comment]
`homebrew/fuse` is not currently a supported tap of Linuxbrew. It would be nice to get it working, but you'll have to either troubleshoot it yourself or find someone to help you troubleshoot it. You could ask over at https://github.com/Homebrew/homebrew-fuse whether they have any interest in supporting Linuxbrew.
