### ISSUE TITLE
Failed on ChromiumOS with wiki instructions: undefined method rebuild

### ISSUE THREAD

**Issue by aghasemi** [Linuxbrew/brew#159]
This is what happened with `brew install hello`

```
Error: undefined method `rebuild' for #<BottleSpecification:0x00559ff04a6cb8>
Please report this bug:
    https://github.com/Linuxbrew/linuxbrew/blob/master/share/doc/homebrew/Troubleshooting.md#troubleshooting
/usr/local/linuxbrew/Library/Taps/homebrew/homebrew-core/Formula/camlistore.rb:11:in `block in <class:Camlistore>'
/usr/local/linuxbrew/Library/Homebrew/software_spec.rb:91:in `instance_eval'
/usr/local/linuxbrew/Library/Homebrew/software_spec.rb:91:in `bottle'
/usr/local/linuxbrew/Library/Homebrew/formula.rb:1729:in `bottle'
/usr/local/linuxbrew/Library/Taps/homebrew/homebrew-core/Formula/camlistore.rb:9:in `<class:Camlistore>'
/usr/local/linuxbrew/Library/Taps/homebrew/homebrew-core/Formula/camlistore.rb:1:in `load_formula'
/usr/local/linuxbrew/Library/Homebrew/formulary.rb:21:in `module_eval'
/usr/local/linuxbrew/Library/Homebrew/formulary.rb:21:in `load_formula'
/usr/local/linuxbrew/Library/Homebrew/formulary.rb:34:in `load_formula_from_path'
/usr/local/linuxbrew/Library/Homebrew/formulary.rb:83:in `load_file'
/usr/local/linuxbrew/Library/Homebrew/formulary.rb:74:in `klass'
/usr/local/linuxbrew/Library/Homebrew/formulary.rb:70:in `get_formula'
/usr/local/linuxbrew/Library/Homebrew/formulary.rb:207:in `factory'
/usr/local/linuxbrew/Library/Homebrew/formula_installer.rb:246:in `block in check_conflicts'
/usr/local/linuxbrew/Library/Homebrew/formula_installer.rb:244:in `select'
/usr/local/linuxbrew/Library/Homebrew/formula_installer.rb:244:in `check_conflicts'
/usr/local/linuxbrew/Library/Homebrew/formula_installer.rb:180:in `install'
/usr/local/linuxbrew/Library/Homebrew/cmd/install.rb:232:in `install_formula'
/usr/local/linuxbrew/Library/Homebrew/cmd/install.rb:93:in `block in install'
/usr/local/linuxbrew/Library/Homebrew/cmd/install.rb:93:in `each'
/usr/local/linuxbrew/Library/Homebrew/cmd/install.rb:93:in `install'
/usr/local/linuxbrew/Library/brew.rb:84:in `<main>'
```

Any idea?

**Comment by sjackman** [comment]
`Error: undefined method 'rebuild'`
It looks as though your `Linuxbrew/brew` is quite out of date. Read the output of `brew doctor` and try `brew update`

**Comment by aghasemi** [comment]
I cloned afresh the git rep. `brew update` followed `brew doctor` seems to have solved it, though this is the output of update:

```
remote: Counting objects: 944, done.
remote: Compressing objects: 100% (843/843), done.
remote: Total 944 (delta 242), reused 413 (delta 79), pack-reused 0
Receiving objects: 100% (944/944), 856.26 KiB | 971.00 KiB/s, done.
Resolving deltas: 100% (242/242), completed with 157 local objects.
From https://github.com/Linuxbrew/brew
 + eec5059...d5f4afa master     -> origin/master  (forced update)
HEAD is now at d5f4afa pull: Squash build-bottle-pr commit for Linuxbrew
/usr/local/linuxbrew/Library/Homebrew/cmd/update.sh: line 6: /usr/local/linuxbrew/Library/ENV/scm/git: No such file or directory
```

**Comment by sjackman** [comment]
`/usr/local/linuxbrew/Library/ENV/scm/git: No such file or directory`
Hopefully this error is transient. Comment here if you see it again.
