### ISSUE TITLE
DependencyCollector.tar_needs_xz_dependency? uses private method xz_dep

### ISSUE THREAD

**Issue by bw-yuhogg** [Linuxbrew/brew#180]
_From @paradox460 on November 28, 2016 2:0_

Trying to install ffmpeg, and it depends on gettext. Looks like merging in 1.0.8 made `#xz_dep` a private method inside dependency collector, in [89696b](https://github.com/Linuxbrew/brew/commit/89696bd4fe11e8fedf6c05d99e8db784f06214ee#diff-d6e8980dbd56c3c8468438181a406381)

```
brew install gettext
==> Downloading https://ftpmirror.gnu.org/gettext/gettext-0.19.8.1.tar.xz
Already downloaded: /home/jeffs/.cache/Homebrew/gettext-0.19.8.1.tar.xz
Error: private method `xz_dep' called for #<DependencyCollector:0x005646388b2160>
Please report this bug:
  https://github.com/Linuxbrew/brew/blob/master/docs/Troubleshooting.md#troubleshooting
/home/jeffs/.linuxbrew/Library/Homebrew/dependency_collector.rb:65:in `tar_needs_xz_dependency?'
/home/jeffs/.linuxbrew/Library/Homebrew/download_strategy.rb:244:in `block in stage'
/home/jeffs/.linuxbrew/Library/Homebrew/utils.rb:255:in `with_system_path'
/home/jeffs/.linuxbrew/Library/Homebrew/download_strategy.rb:243:in `stage'
/home/jeffs/.linuxbrew/Library/Homebrew/resource.rb:95:in `block in unpack'
/home/jeffs/.linuxbrew/Library/Homebrew/extend/fileutils.rb:14:in `block in mktemp'
/home/jeffs/.linuxbrew/Library/Homebrew/extend/fileutils.rb:74:in `block in run'
/home/jeffs/.linuxbrew/Library/Homebrew/extend/fileutils.rb:74:in `chdir'
/home/jeffs/.linuxbrew/Library/Homebrew/extend/fileutils.rb:74:in `run'
/home/jeffs/.linuxbrew/Library/Homebrew/extend/fileutils.rb:13:in `mktemp'
/home/jeffs/.linuxbrew/Library/Homebrew/resource.rb:94:in `unpack'
/home/jeffs/.linuxbrew/Library/Homebrew/resource.rb:86:in `stage'
/home/jeffs/.linuxbrew/Library/Homebrew/formula.rb:1799:in `stage'
/home/jeffs/.linuxbrew/Library/Homebrew/formula.rb:1075:in `brew'
/home/jeffs/.linuxbrew/Library/Homebrew/build.rb:112:in `install'
/home/jeffs/.linuxbrew/Library/Homebrew/build.rb:187:in `<main>'
```

_Copied from original issue: Linuxbrew/homebrew-core#1220_

**Comment by bw-yuhogg** [comment]
@paradox460, thanks a bunch for reporting!

This is an OS-dependent bug. It doesn't affect macOS because that defines a public `xz_dep` method in `extend/os/mac/dependency_collector.rb`.

Creating a similar file for Linux should resolve this issue.

**Comment by bw-yuhogg** [comment]
I've opened #181 to resolve this issue. Once CI passes, I'll merge it in.

Thanks once again for finding this bug @paradox460! 😸 

EDIT: I've proposed https://github.com/Homebrew/brew/pull/1588 upstream, which is a better fix IMO. If that PR is accepted, I'll cherry-pick the commit(s) here instead of merging this.

**Comment by paradox460** [comment]
Awesome, thank you!
