### ISSUE TITLE
brew upgrade error

### ISSUE THREAD

**Issue by yzhzu** [Linuxbrew/brew#193]
```
brew upgrade
Error: Calling Formula.sha1 is disabled!
Use Formula.sha256 instead.
/home/rcmm/.linuxbrew/Library/Taps/chapmanb/homebrew-cbl/bcbio-rnaseq.rb:7:in `<class:BcbioRnaseq>'
Please report this to the chapmanb/cbl tap!
Please report this bug:
  https://github.com/Linuxbrew/brew/blob/master/docs/Troubleshooting.md#troubleshooting
/home/rcmm/.linuxbrew/Library/Homebrew/utils.rb:86:in `odeprecated'
/home/rcmm/.linuxbrew/Library/Homebrew/utils.rb:94:in `odisabled'
/home/rcmm/.linuxbrew/Library/Homebrew/compat/sha1.rb:3:in `sha1'
/home/rcmm/.linuxbrew/Library/Taps/chapmanb/homebrew-cbl/bcbio-rnaseq.rb:7:in `<class:BcbioRnaseq>'
/home/rcmm/.linuxbrew/Library/Taps/chapmanb/homebrew-cbl/bcbio-rnaseq.rb:3:in `load_formula'
/home/rcmm/.linuxbrew/Library/Homebrew/formulary.rb:25:in `module_eval'
/home/rcmm/.linuxbrew/Library/Homebrew/formulary.rb:25:in `load_formula'
/home/rcmm/.linuxbrew/Library/Homebrew/formulary.rb:42:in `load_formula_from_path'
/home/rcmm/.linuxbrew/Library/Homebrew/formulary.rb:97:in `load_file'
/home/rcmm/.linuxbrew/Library/Homebrew/formulary.rb:88:in `klass'
/home/rcmm/.linuxbrew/Library/Homebrew/formulary.rb:84:in `get_formula'
/home/rcmm/.linuxbrew/Library/Homebrew/formulary.rb:201:in `get_formula'
/home/rcmm/.linuxbrew/Library/Homebrew/formulary.rb:241:in `factory'
/home/rcmm/.linuxbrew/Library/Homebrew/formulary.rb:272:in `from_keg'
/home/rcmm/.linuxbrew/Library/Homebrew/formulary.rb:255:in `from_rack'
/home/rcmm/.linuxbrew/Library/Homebrew/formula.rb:1364:in `block in installed'
/home/rcmm/.linuxbrew/Library/Homebrew/formula.rb:1362:in `map'
/home/rcmm/.linuxbrew/Library/Homebrew/formula.rb:1362:in `installed'
/home/rcmm/.linuxbrew/Library/Homebrew/cmd/upgrade.rb:37:in `upgrade'
/home/rcmm/.linuxbrew/Library/Homebrew/brew.rb:94:in `<main>'
[rcmm@localhost ~]$ ^C
```

**Comment by sjackman** [comment]
Please report this issue to the chapmanb/cbl tap.
