### ISSUE TITLE
Error: stack level too deep

### ISSUE THREAD

**Issue by jwhite007** [Linuxbrew/brew#240]
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [x] Confirmed this is problem with Homebrew/brew and not specific formulae? If it's a formulae-specific problem please file this issue at https://github.com/Homebrew/homebrew-core/issues/new

This may be due to something that our IT has done, unbeknownst to me. As far as I know, since the last time that brew ran successfully nothing has changed at the system level.

### Bug reports:
```
$ brew upgrade
Error: stack level too deep
Please report this bug:
  https://github.com/Linuxbrew/brew/blob/master/docs/Troubleshooting.md#troubleshooting
/toolbox/NGS/.linuxbrew/Library/Homebrew/tap.rb:28
```
`brew dr` gives same output.
```
$ brew config
HOMEBREW_VERSION: 1.1.6-5-ga8dff1fe6
ORIGIN: https://github.com/Linuxbrew/brew
HEAD: a8dff1fe61193bacfd8416e8cd024803a59802d0
Last commit: 7 days ago
Core tap ORIGIN: https://github.com/Linuxbrew/homebrew-core
Core tap HEAD: 72349992f3f8c6d47ed76ee26d854e63e7550d42
Core tap last commit: 3 days ago
HOMEBREW_PREFIX: /toolbox/NGS/.linuxbrew
HOMEBREW_REPOSITORY: /toolbox/NGS/.linuxbrew
HOMEBREW_CELLAR: /toolbox/NGS/.linuxbrew/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://linuxbrew.bintray.com
CPU: octa-core 64-bit merom
Homebrew Ruby: 2.0.0-p648 => /toolbox/NGS/.linuxbrew/Library/Homebrew/vendor/portable-ruby/2.0.0-p648/bin/ruby
Clang: N/A
Git: 2.11.0 => /toolbox/NGS/.linuxbrew/bin/git
Perl: /toolbox/NGS/.linuxbrew/bin/perl => /toolbox/NGS/.linuxbrew/Cellar/perl/5.24.0_3/bin/perl
Python: /toolbox/NGS/.linuxbrew/bin/python => /toolbox/NGS/.linuxbrew/Cellar/python/2.7.13/bin/python2.7
Ruby: /toolbox/NGS/.linuxbrew/bin/ruby => /toolbox/NGS/.linuxbrew/Cellar/ruby/2.4.0/bin/ruby
Java: 1.8.0_112
Kernel: Linux 2.6.32-504.el6.x86_64 x86_64 GNU/Linux
OS: Red Hat Enterprise Linux Server release 6.6 (Santiago)
Codename: Santiago
OS glibc: 2.12
OS gcc: 4.4.7
Linuxbrew glibc: 2.19
Linuxbrew gcc: 5.3.0
Linuxbrew xorg: N/A
```

```
$ ulimit -a
core file size          (blocks, -c) 0
data seg size           (kbytes, -d) unlimited
scheduling priority             (-e) 0
file size               (blocks, -f) unlimited
pending signals                 (-i) 127431
max locked memory       (kbytes, -l) 64
max memory size         (kbytes, -m) unlimited
open files                      (-n) 1024
pipe size            (512 bytes, -p) 8
POSIX message queues     (bytes, -q) 819200
real-time priority              (-r) 0
stack size              (kbytes, -s) 10240
cpu time               (seconds, -t) unlimited
max user processes              (-u) 4096
virtual memory          (kbytes, -v) unlimited
file locks                      (-x) unlimited
```

**Comment by bw-yuhogg** [comment]
I can reproduce this now too. I **suspect** that it's related to all the recent deprecations happening on Homebrew: formulae in taps like homebrew/python and homebrew/x11 have been migrated to homebrew/core.

For context, here's the error backtrace I get:
```
Error: stack level too deep
Please report this bug:
  https://github.com/Linuxbrew/brew/blob/master/docs/Troubleshooting.md#troubleshooting
/home/linuxbrew/.linuxbrew/Cellar/ruby/2.4.0/lib/ruby/2.4.0/pathname.rb:44:in `chop_basename'
/home/linuxbrew/.linuxbrew/Cellar/ruby/2.4.0/lib/ruby/2.4.0/pathname.rb:358:in `plus'
/home/linuxbrew/.linuxbrew/Cellar/ruby/2.4.0/lib/ruby/2.4.0/pathname.rb:350:in `+'
/home/linuxbrew/.linuxbrew/Library/Homebrew/formulary.rb:176:in `formula_name_path'
/home/linuxbrew/.linuxbrew/Library/Homebrew/formulary.rb:194:in `formula_name_path'
/home/linuxbrew/.linuxbrew/Library/Homebrew/formulary.rb:194:in `formula_name_path'
... <more of the same>...
```

If I'm right, a merge from homebrew/core to linuxbrew/core should resolve this.

**Comment by jwhite007** [comment]
@rwhogg 

Bob,

Thanks for the response. I'm not sure that a merge as you suggested has been done, but the issues is resolved. `brew upgrade` is now working as expected.

**Comment by bw-yuhogg** [comment]
> Thanks for the response. I'm not sure that a merge as you suggested has been done

It was: @sjackman did so on Saturday. Thanks again Shaun!

**Comment by jwhite007** [comment]
@sjackman 

Ditto rwhogg... Thanks, Shaun!
