### ISSUE TITLE
Inconsistency detected by ld.so: get-dynamic-info.h: 134: elf_get_dynamic_info: Assertion `info[15] == ((void *)0)' failed!

### ISSUE THREAD

**Issue by houghjosh** [Linuxbrew/brew#266]
### Error: cannot be built with any available compilers. 

! keep running into this error:

```
 Inconsistency detected by ld.so: get-dynamic-info.h: 134: elf_get_dynamic_info: Assertion `info[15] == ((void *)0)' failed!

Error: [some software] cannot be built with any available compilers.
```

for example:

```
brew install htop
==> Installing dependencies for htop: pkg-config, homebrew/dupes/ncurses
==> Installing htop dependency: pkg-config
Inconsistency detected by ld.so: get-dynamic-info.h: 134: elf_get_dynamic_info: Assertion `info[15] == ((void *)0)' failed!
Inconsistency detected by ld.so: get-dynamic-info.h: 134: elf_get_dynamic_info: Assertion `info[15] == ((void *)0)' failed!
Error: pkg-config cannot be built with any available compilers.
Install Clang or brew install gcc
```

The error is thrown when I try to install other software too, not just htop. 

OK, so check if I have gcc

```
$ which gcc
~/.linuxbrew/bin/gcc
```

looks fine

```
brew install gcc
Warning: gcc-5.3.0 already installed
```
It's installed, but doesn't appear to be working?

There's nothing obvious to me from `brew doctor`....

```
$ brew doctor
Warning: Unbrewed header files were found in /usr/local/include.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.
Unexpected header files:
  /usr/local/include/jellyfish-2.2.5/jellyfish/json.h

Warning: Unbrewed .la files were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected .la files:
  /usr/local/lib/libjellyfish-2.0.la

Warning: Unbrewed .pc files were found in /usr/local/lib/pkgconfig.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected .pc files:
  /usr/local/lib/pkgconfig/jellyfish-2.0.pc

Warning: Unbrewed static libraries were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected static libraries:
  /usr/local/lib/libjellyfish-2.0.a
```

Anyone know how to fix this? I've tried everything I can think of, including fresh install of linuxbrew, reinstalling gcc, uninstalling gcc and trying to use the unbrewed version on my machine, etc etc.

**Comment by sjackman** [comment]
Sorry for the delay in my reply. Please report the output of
```sh
ls -l $(brew --prefix)/lib/ld.so
realpath $(brew --prefix)/lib/ld.so
env | grep LD_
brew install pkg-config
brew gist-logs pkg-config
```

**Comment by houghjosh** [comment]
Thanks for the reply. I think the issue had to do with my version of `glibc`, which apparently should be version 2.19 or greater to use the precompiled binaries. I've since set `export HOMEBREW_BUILD_FROM_SOURCE=1` and am able to do install software (e.g. pkg-config) building everything from source. It's not as good, but it works. I'm still curious if there's another work-around though. 

Here is the output from the command(s) above:

```
[josh.hough@capsicum ~]$ ls -l $(brew --prefix)/lib/ld.so
lrwxrwxrwx. 1 josh.hough josh.hough 70 Feb 22 19:08 /cap1/josh.hough/.linuxbrew/lib/ld.so -> /cap1/josh.hough/.linuxbrew/Cellar/glibc/2.19/lib/ld-linux-x86-64.so.2

[josh.hough@capsicum ~]$ ls -l $(brew --prefix)/lib/ld.so
lrwxrwxrwx. 1 josh.hough josh.hough 70 Feb 22 19:08 /cap1/josh.hough/.linuxbrew/lib/ld.so -> /cap1/josh.hough/.linuxbrew/Cellar/glibc/2.19/lib/ld-linux-x86-64.so.2

[josh.hough@capsicum ~]$ realpath $(brew --prefix)/lib/ld.so
/cap1/josh.hough/.linuxbrew/Cellar/glibc/2.19/lib/ld-2.19.so

[josh.hough@capsicum ~]$ env | grep LD_
LD_LIBRARY_PATH=/cag/programs/SHOREmap/dislin

[josh.hough@capsicum ~]$ brew install pkg-config
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 2 taps (homebrew/core, homebrew/science).
No changes to formulae.
Warning: pkg-config-0.29.1_2 already installed

[josh.hough@capsicum ~]$ brew gist-logs pkg-config
Error: Your HOMEBREW_GITHUB_API_TOKEN does not have sufficient scope!
Scopes they need: gist
Scopes it has:
Create a new personal access token: https://github.com/settings/tokens/new?scopes=gist,public_repo&description=Homebrew
and then set the new HOMEBREW_GITHUB_API_TOKEN as the authentication method instead.
/cap1/josh.hough/.linuxbrew/Library/Homebrew/utils/github.rb:218:in `raise_api_error': GitHub::HTTPNotFoundError
	from /cap1/josh.hough/.linuxbrew/Library/Homebrew/utils/github.rb:184:in `open'
	from /cap1/josh.hough/.linuxbrew/Library/Homebrew/cmd/gist-logs.rb:114:in `create_gist'
	from /cap1/josh.hough/.linuxbrew/Library/Homebrew/cmd/gist-logs.rb:46:in `gistify_logs'
	from /cap1/josh.hough/.linuxbrew/Library/Homebrew/cmd/gist-logs.rb:127:in `gist_logs'
	from /cap1/josh.hough/.linuxbrew/Library/Homebrew/brew.rb:94:in `<main>' 
```

**Comment by sjackman** [comment]
If you start over with a fresh install of Linuxbrew, and the first thing you do is `brew install gcc`, you should be able to use precompiled bottles.

Please follow the advice above about create a personal access token on GitHub:
> Create a new personal access token: https://github.com/settings/tokens/new?scopes=gist,public_repo&description=Homebrew
and then set the new HOMEBREW_GITHUB_API_TOKEN as the authentication method instead.

**Comment by houghjosh** [comment]
Yeah, I tried a fresh linuxbrew install followed by `brew install gcc`  a couple of times. It doesn't work. `gcc` will install, or it will say it is installed, but as soon as I try to install something that requires it, e.g., `brew install htop`, the error above is thrown, saying it cannot be built with any available compilers.

**Comment by sjackman** [comment]
Unset the `LD_LIBRARY_PATH` environment variable and any other variables starting with `LD_`, and please report `brew gist-logs pkg-config` after setting your `HOMEBREW_GITHUB_API_TOKEN`.
