### ISSUE TITLE
Brew Doctor - Error: "cxx14" is not a recognized standard

### ISSUE THREAD

**Issue by greenstick** [Linuxbrew/brew#331]
### Bug report:

I went to install the `python3` formula and, prior to doing so, ran `brew update` (old habits die hard) and `brew doctor`. The warnings in the `brew doctor` output are not new – I generally ignore them as I don't have administration privileges to address them and they have never caused any problems – however, there was an unusual error (see output below). 

I decided to go ahead and try running the `python3` formula, but also received an error. The formula indicated that my Python 3 version (`~/.linuxbrew/bin/python3`) is not >= 2.5. I checked  `~/.linuxbrew/bin` to see if the python3 executable being called was there (seemed strange that the formula would try and call it after all), and it wasn't; Python 2.7 (`python2.7`) is installed in that location. I realize this may be separate to the issue above and specific to the `python3` formula.

I've attached the output of `brew doctor`, `brew config`, as well as `brew install python3` below. Let me know if there are any additional details I can provide. 

Thanks!

```
#
# Brew Doctor
#

[user@exalab3 .linuxbrew]$ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!

Warning: Setting LD_* vars can break dynamic linking.
Set variables:
  LD_LIBRARY_PATH: /opt/openmpi/lib:/state/partition2/opt/installed/ngs-1.3.0/lib64:/state/partition2/opt/installed/vdb-2.8.0/lib64:

Warning: "config" scripts exist outside your system or Homebrew directories.
`./configure` scripts often look for *-config scripts to determine if
software packages are installed, and what additional flags to use when
compiling and linking.

Having additional scripts in your path can confuse software installed via
Homebrew if the config script overrides a system or Homebrew provided
script of the same name. We found the following "config" scripts:
  /home/users/user/packages/miniconda/bin/python-config
  /usr/local/bin/vdb-config
  /opt/ganglia/bin/ganglia-config
  /opt/rocks/bin/python-config
  /opt/rocks/bin/python2.6-config
  /opt/rocks/bin/xml2-config

Warning: Unbrewed header files were found in /usr/local/include.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected header files:
  /usr/local/include/bam/sam_header.h
  /usr/local/include/bam/sam.h
  /usr/local/include/bam/kstring.h
  /usr/local/include/bam/sample.h
  /usr/local/include/bam/bam_tview.h
  /usr/local/include/bam/kprobaln.h
  /usr/local/include/bam/faidx.h
  /usr/local/include/bam/kaln.h
  /usr/local/include/bam/khash.h
  /usr/local/include/bam/ksort.h
  /usr/local/include/bam/bam_endian.h
  /usr/local/include/bam/bgzf.h
  /usr/local/include/bam/bam.h
  /usr/local/include/bam/errmod.h
  /usr/local/include/bam/klist.h
  /usr/local/include/bam/kseq.h
  /usr/local/include/bam/razf.h
  /usr/local/include/bam/bam2bcf.h
  /usr/local/include/bam/knetfile.h

Warning: Unbrewed static libraries were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected static libraries:
  /usr/local/lib/libbam.a

# The New Error - Looking Up cxx14, it Looks to be Related to R and Perhaps C++14
Error: "cxx14" is not a recognized standard
Please report this bug:
  https://github.com/Linuxbrew/brew/blob/master/docs/Troubleshooting.md#troubleshooting
/home/users/user/.linuxbrew/Library/Homebrew/compilers.rb:37:in `block in for_standard'
/home/users/user/.linuxbrew/Library/Homebrew/compilers.rb:36:in `fetch'
/home/users/user/.linuxbrew/Library/Homebrew/compilers.rb:36:in `for_standard'
/home/users/user/.linuxbrew/Library/Homebrew/software_spec.rb:183:in `block in needs'
/home/users/user/.linuxbrew/Library/Homebrew/software_spec.rb:182:in `each'
/home/users/user/.linuxbrew/Library/Homebrew/software_spec.rb:182:in `needs'
/home/users/user/.linuxbrew/Library/Homebrew/formula.rb:2396:in `block in needs'
/home/users/user/.linuxbrew/Library/Homebrew/formula.rb:2396:in `each'
/home/users/user/.linuxbrew/Library/Homebrew/formula.rb:2396:in `needs'
/home/users/user/.linuxbrew/Library/Taps/homebrew/homebrew-science/kmc.rb:24:in `<class:Kmc>'
/home/users/user/.linuxbrew/Library/Taps/homebrew/homebrew-science/kmc.rb:1:in `load_formula'
/home/users/user/.linuxbrew/Library/Homebrew/formulary.rb:26:in `module_eval'
/home/users/user/.linuxbrew/Library/Homebrew/formulary.rb:26:in `load_formula'
/home/users/user/.linuxbrew/Library/Homebrew/formulary.rb:46:in `load_formula_from_path'
/home/users/user/.linuxbrew/Library/Homebrew/formulary.rb:101:in `load_file'
/home/users/user/.linuxbrew/Library/Homebrew/formulary.rb:218:in `load_file'
/home/users/user/.linuxbrew/Library/Homebrew/formulary.rb:92:in `klass'
/home/users/user/.linuxbrew/Library/Homebrew/formulary.rb:88:in `get_formula'
/home/users/user/.linuxbrew/Library/Homebrew/formulary.rb:212:in `get_formula'
/home/users/user/.linuxbrew/Library/Homebrew/formulary.rb:259:in `factory'
/home/users/user/.linuxbrew/Library/Homebrew/formulary.rb:290:in `from_keg'
/home/users/user/.linuxbrew/Library/Homebrew/formulary.rb:273:in `from_rack'
/home/users/user/.linuxbrew/Library/Homebrew/formula.rb:1425:in `block in installed'
/home/users/user/.linuxbrew/Library/Homebrew/formula.rb:1423:in `map'
/home/users/user/.linuxbrew/Library/Homebrew/formula.rb:1423:in `installed'
/home/users/user/.linuxbrew/Library/Homebrew/diagnostic.rb:935:in `check_missing_deps'
/home/users/user/.linuxbrew/Library/Homebrew/cmd/doctor.rb:43:in `block in doctor'
/home/users/user/.linuxbrew/Library/Homebrew/cmd/doctor.rb:35:in `each'
/home/users/user/.linuxbrew/Library/Homebrew/cmd/doctor.rb:35:in `doctor'
/home/users/user/.linuxbrew/Library/Homebrew/brew.rb:94:in `<main>'

#
# Brew Config
#

[user@exalab3 .linuxbrew]$ brew config
HOMEBREW_VERSION: 1.1.10
ORIGIN: https://github.com/Linuxbrew/brew
HEAD: d8c8b867bf99c604c89bc848f58d1fae8afd599c
Last commit: 7 weeks ago
Core tap ORIGIN: https://github.com/Linuxbrew/homebrew-core
Core tap HEAD: f2a4c8a469b01d0f04467f29ac1ce78e8ac2c10e
Core tap last commit: 37 minutes ago
HOMEBREW_PREFIX: /home/users/user/.linuxbrew
HOMEBREW_REPOSITORY: /home/users/user/.linuxbrew
HOMEBREW_CELLAR: /home/users/user/.linuxbrew/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://linuxbrew.bintray.com
CPU: 32-core 64-bit sandybridge
Homebrew Ruby: 2.0.0-p648 => /home/users/user/.linuxbrew/Library/Homebrew/vendor/portable-ruby/2.0.0-p648/bin/ruby
Clang: 3.4 build
Git: 2.10.1 => /home/users/user/.linuxbrew/bin/git
Perl: /home/users/user/.linuxbrew/bin/perl => /home/users/user/.linuxbrew/Cellar/perl/5.24.0_3/bin/perl
Python: /home/users/user/.linuxbrew/bin/python => /home/users/user/.linuxbrew/Cellar/python/2.7.12_3/bin/python2.7
Ruby: /home/users/user/packages/miniconda/bin/ruby
Java: 1.8.0_112
Kernel: Linux 2.6.32-504.12.2.el6.x86_64 x86_64 GNU/Linux
OS: CentOS release 6.5 (Final)
Codename: Final
OS glibc: 2.12
OS gcc: 4.4.7
Linuxbrew glibc: 2.19
Linuxbrew gcc: 5.3.0
Linuxbrew xorg: N/A

#
# Brew Install Python 3
#

[user@exalab3 .linuxbrew]$ brew install python3
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 1 tap (homebrew/core).
No changes to formulae.

Warning: Use unzip instead of deprecated homebrew/dupes/unzip
Warning: Use unzip instead of deprecated homebrew/dupes/unzip
Warning: Use unzip instead of deprecated homebrew/dupes/unzip
Warning: Use unzip instead of deprecated homebrew/dupes/unzip
Warning: Use unzip instead of deprecated homebrew/dupes/unzip
Warning: Use unzip instead of deprecated homebrew/dupes/unzip
Warning: Use unzip instead of deprecated homebrew/dupes/unzip
Warning: Use unzip instead of deprecated homebrew/dupes/unzip
Warning: Use unzip instead of deprecated homebrew/dupes/unzip
Warning: Use unzip instead of deprecated homebrew/dupes/unzip
Warning: Use unzip instead of deprecated homebrew/dupes/unzip
Warning: Use unzip instead of deprecated homebrew/dupes/unzip
Warning: Use unzip instead of deprecated homebrew/dupes/unzip
Warning: Use unzip instead of deprecated homebrew/dupes/unzip
Warning: Use unzip instead of deprecated homebrew/dupes/unzip
Warning: Use unzip instead of deprecated homebrew/dupes/unzip
Warning: Use unzip instead of deprecated homebrew/dupes/unzip
Warning: Use unzip instead of deprecated homebrew/dupes/unzip
Warning: Use unzip instead of deprecated homebrew/dupes/unzip
Warning: Use unzip instead of deprecated homebrew/dupes/unzip
Warning: Use unzip instead of deprecated homebrew/dupes/unzip
Warning: Use unzip instead of deprecated homebrew/dupes/unzip
Warning: Use unzip instead of deprecated homebrew/dupes/unzip
Warning: Use unzip instead of deprecated homebrew/dupes/unzip
Warning: Use unzip instead of deprecated homebrew/dupes/unzip
==> Installing dependencies for python3: pkg-config, ncurses, readline, sqlite, gdbm, libffi
==> Installing python3 dependency: pkg-config
==> Downloading https://pkgconfig.freedesktop.org/releases/pkg-config-0.29.2.tar.gz
Already downloaded: /home/users/user/.cache/Homebrew/pkg-config-0.29.2.tar.gz
==> ./configure --prefix=/home/users/user/.linuxbrew/Cellar/pkg-config/0.29.2 --disable-host-tool --with-internal-glib --with-pc-path=/home/users/user/.linuxbrew/lib/pkgconfig:/home/users/cordier/.l
Last 15 lines from /home/users/user/.cache/Homebrew/Logs/pkg-config/01.configure:
checking whether to enable garbage collector friendliness... no
checking whether to disable memory pools... no
checking whether we are using the GNU C++ compiler... yes
checking whether /home/users/cordier/.linuxbrew/bin/g++-5 accepts -g... yes
checking dependency style of /home/users/cordier/.linuxbrew/bin/g++-5... gcc3
checking for special C compiler options needed for large files... no
checking for _FILE_OFFSET_BITS value needed for large files... no
checking for gawk... (cached) gawk
checking for perl5... no
checking for perl... perl
checking for indent... indent
checking for perl... /home/users/user/.linuxbrew/bin/perl
checking whether /home/users/user/.linuxbrew/bin/./python3 version is >= 2.5... no
configure: error: Python interpreter is too old
configure: error: ./configure failed for glib

READ THIS: https://github.com/Linuxbrew/brew/blob/master/docs/Troubleshooting.md#troubleshooting
```

**Comment by sjackman** [comment]
```
/home/users/user/.linuxbrew/Library/Taps/homebrew/homebrew-science/kmc.rb:24
```
`kmc` has the line `needs :cxx14`, but `brew` 1.1.10 doesn't support that statement. `brew` 1.1.11 will, and we expect to release it soon. It's unrelated however to your Python issue.

If `pkg-config` depends on Python, that's an interesting chicken and egg problem, because `python` depends on `pkg-config`.

**Comment by greenstick** [comment]
That's good to hear – I'll wait for the `brew` update. And yes, I suspected the Python issue was a chicken and egg problem, odd. I'll look into it further and report back if I find a fix.

**Comment by sjackman** [comment]
I believe this issue is resolved.
