### ISSUE TITLE
Error: integer 2303867802 too big to convert to `int'

### ISSUE THREAD

**Issue by Anikakp** [Linuxbrew/brew#364]
Error while install jq through brew command. 

brew install jq

```
Installing dependencies for jq: patchelf, zlib, binutils, linux-headers, glibc, xz, gmp, mpfr, libmpc, isl, gcc, oniguruma
==> Installing jq dependency: patchelf
==> Downloading https://linuxbrew.bintray.com/bottles/patchelf-0.9_1.x86_64_linux.bottle.tar.gz
Already downloaded: /home/anika_prakash/.cache/Homebrew/patchelf-0.9_1.x86_64_linux.bottle.tar.gz
==> Pouring patchelf-0.9_1.x86_64_linux.bottle.tar.gz
Error: integer 2303867802 too big to convert to `int'
Warning: Bottle installation failed: building from source.
==> Downloading http://nixos.org/releases/patchelf/patchelf-0.9/patchelf-0.9.tar.gz
Already downloaded: /home/anika_prakash/.cache/Homebrew/patchelf-0.9.tar.gz
Error: integer 2303867802 too big to convert to `int'
Please report this bug:
  https://github.com/Linuxbrew/brew/blob/master/docs/Troubleshooting.md#troubleshooting
/home/anika_prakash/.linuxbrew/Library/Homebrew/extend/pathname.rb:187:in `atomic_write'
/home/anika_prakash/.linuxbrew/Library/Homebrew/utils/inreplace.rb:34:in `block in inreplace'
/home/anika_prakash/.linuxbrew/Library/Homebrew/utils/inreplace.rb:22:in `each'
/home/anika_prakash/.linuxbrew/Library/Homebrew/utils/inreplace.rb:22:in `inreplace'
/home/anika_prakash/.linuxbrew/Library/Taps/homebrew/homebrew-core/Formula/patchelf.rb:27:in `install'
/home/anika_prakash/.linuxbrew/Library/Homebrew/build.rb:150:in `block in install'
/home/anika_prakash/.linuxbrew/Library/Homebrew/formula.rb:1137:in `block in brew'
/home/anika_prakash/.linuxbrew/Library/Homebrew/formula.rb:1930:in `block in stage'
/home/anika_prakash/.linuxbrew/Library/Homebrew/resource.rb:98:in `block in unpack'
/home/anika_prakash/.linuxbrew/Library/Homebrew/extend/fileutils.rb:14:in `block in mktemp'
/home/anika_prakash/.linuxbrew/Library/Homebrew/extend/fileutils.rb:74:in `block in run'
/home/anika_prakash/.linuxbrew/Library/Homebrew/extend/fileutils.rb:74:in `chdir'
/home/anika_prakash/.linuxbrew/Library/Homebrew/extend/fileutils.rb:74:in `run'
/home/anika_prakash/.linuxbrew/Library/Homebrew/extend/fileutils.rb:13:in `mktemp'
/home/anika_prakash/.linuxbrew/Library/Homebrew/resource.rb:94:in `unpack'
/home/anika_prakash/.linuxbrew/Library/Homebrew/resource.rb:86:in `stage'
/home/anika_prakash/.linuxbrew/Library/Homebrew/formula.rb:1917:in `stage'
/home/anika_prakash/.linuxbrew/Library/Homebrew/formula.rb:1132:in `brew'
/home/anika_prakash/.linuxbrew/Library/Homebrew/build.rb:125:in `install'
/home/anika_prakash/.linuxbrew/Library/Homebrew/build.rb:202:in `<main>'
```

**Comment by sjackman** [comment]
Please report
```sh
brew gist-logs patchelf
```

**Comment by Anikakp** [comment]
https://gist.github.com/anonymous/2d06db95a977cb53dd683225cb7f0e10

**Comment by sjackman** [comment]
That's an awfully strange error. I haven't seen it before.
```
/home/anika_prakash/.linuxbrew/Library/Homebrew/extend/pathname.rb:187:in `atomic_write'
```
```ruby
tf.chown(uid, gid)
```

Please report
```sh
id
which -a ruby
/usr/bin/ruby --version
/home/anika_prakash/.linuxbrew/Library/Homebrew/vendor/portable-ruby/2.0.0-p648/bin/ruby --version
```

**Comment by sjackman** [comment]
Please also report
```sh
which -a irb
irb --version
irb
```
```ruby
Process.uid
Process.gid
Process.groups.delete(old_stat.gid) { Process.gid }
```
