### ISSUE TITLE
brew search results in 'Error: Broken pipe'

### ISSUE THREAD

**Issue by seanjensengrey** [Linuxbrew/brew#38]
`brew search gcc`
sporadically has two different results
## broken result

```
gcc                                                                                       homebrew/dupes/apple-gcc42                                                              
Error: Broken pipe
```
## correct result

```
gcc                                                                                       homebrew/dupes/apple-gcc42                                                              
homebrew/versions/gcc43             homebrew/versions/gcc45             homebrew/versions/gcc47             homebrew/versions/gcc49             homebrew/versions/gcc6            
homebrew/versions/gcc44             homebrew/versions/gcc46             homebrew/versions/gcc48             homebrew/versions/gcc5              homebrew/versions/llvm-gcc28      
```

90%+ of the output results in `Error: Broken pipe`

**Comment by sjackman** [comment]
I haven't seen this error and can't reproduce it with `brew search`, but I have seen this error with `brew audit`. See #29. I don't unfortunately know what's causing it.

**Comment by seanjensengrey** [comment]
This instance `ssh ubuntu@52.87.199.241` exhibits the bug.  Nothing is sacred on this machine.

**Comment by sjackman** [comment]
It certainly reproduces the error.

```
$ brew search gcc -d
/home/ubuntu/.linuxbrew/Library/brew.rb (Formulary::FormulaLoader): loading /home/ubuntu/.linuxbrew/Library/Taps/homebrew/homebrew-core/Formula/gcc.rb
/home/ubuntu/.linuxbrew/Library/brew.rb (Formulary::FormulaLoader): loading /home/ubuntu/.linuxbrew/Library/Taps/homebrew/homebrew-core/Formula/glibc.rb
/home/ubuntu/.linuxbrew/Library/brew.rb (Formulary::TapLoader): loading /home/ubuntu/.linuxbrew/Library/Taps/homebrew/homebrew-dupes/apple-gcc42.rb
gcc                                      homebrew/dupes/apple-gcc42             
Error: Broken pipe
/home/ubuntu/.linuxbrew/Library/Homebrew/utils.rb:573:in `write'
/home/ubuntu/.linuxbrew/Library/Homebrew/utils.rb:573:in `puts'
/home/ubuntu/.linuxbrew/Library/Homebrew/utils.rb:573:in `block in api_credentials'
/home/ubuntu/.linuxbrew/Library/Homebrew/utils/popen.rb:18:in `block in popen'
/home/ubuntu/.linuxbrew/Library/Homebrew/utils/popen.rb:15:in `popen'
/home/ubuntu/.linuxbrew/Library/Homebrew/utils/popen.rb:15:in `popen'
/home/ubuntu/.linuxbrew/Library/Homebrew/utils.rb:572:in `api_credentials'
/home/ubuntu/.linuxbrew/Library/Homebrew/utils.rb:643:in `open'
/home/ubuntu/.linuxbrew/Library/Homebrew/cmd/search.rb:130:in `block in search_tap'
/home/ubuntu/.linuxbrew/Library/Homebrew/cmd/search.rb:147:in `yield'
/home/ubuntu/.linuxbrew/Library/Homebrew/cmd/search.rb:147:in `default'
/home/ubuntu/.linuxbrew/Library/Homebrew/cmd/search.rb:147:in `search_tap'
/home/ubuntu/.linuxbrew/Library/Homebrew/cmd/search.rb:114:in `block (2 levels) in search_taps'
```

**Comment by sjackman** [comment]
I believe I've found the source of the problem:
https://github.com/Linuxbrew/brew/blob/master/Library/Homebrew/utils.rb#L572-L573

``` ruby
        github_credentials = Utils.popen("git credential-osxkeychain get", "w+") do |io|
          io.puts "protocol=https\nhost=github.com"
          io.close_write
          io.read
        end
```

This code should do something else on Linuxbrew. As a workaround, set the environment variable `HOMEBREW_GITHUB_API_TOKEN` to a GitHub OAuth token.

**Comment by seanjensengrey** [comment]
I accidentally removed this instance. If you need it back. Ping me.  Great work btw, Thanks!

**Comment by sjackman** [comment]
I haven't yet tested, but I suspect that unsetting `HOMEBREW_GITHUB_API_TOKEN` will reproduce this issue for me. Does setting `HOMEBREW_GITHUB_API_TOKEN` resolve this issue for you?

**Comment by seanjensengrey** [comment]
Confirmed, setting `HOMEBREW_GITHUB_API_TOKEN` makes the `Error: Broken pipe` go away and the results of search queries are always complete.

**Comment by sjackman** [comment]
I'm glad to hear that the workaround resolves the issue for you. I'm reopening this issue to hopefully identify the root cause.
