### ISSUE TITLE
undefined method `rebuild'

### ISSUE THREAD

**Issue by Tejeshwarabm** [Linuxbrew/brew#405]
```
/home/admin1/.linuxbrew/Library/Taps/homebrew/homebrew-core/Formula/python3.rb:9:in `block in <class:Python3>'
/home/admin1/.linuxbrew/Library/Homebrew/software_spec.rb:91:in `instance_eval'
/home/admin1/.linuxbrew/Library/Homebrew/software_spec.rb:91:in `bottle'
/home/admin1/.linuxbrew/Library/Homebrew/formula.rb:1729:in `bottle'
/home/admin1/.linuxbrew/Library/Taps/homebrew/homebrew-core/Formula/python3.rb:8:in `<class:Python3>'
/home/admin1/.linuxbrew/Library/Taps/homebrew/homebrew-core/Formula/python3.rb:1:in `load_formula'
/home/admin1/.linuxbrew/Library/Homebrew/formulary.rb:21:in `module_eval'
/home/admin1/.linuxbrew/Library/Homebrew/formulary.rb:21:in `load_formula'
/home/admin1/.linuxbrew/Library/Homebrew/formulary.rb:34:in `load_formula_from_path'
/home/admin1/.linuxbrew/Library/Homebrew/formulary.rb:83:in `load_file'
/home/admin1/.linuxbrew/Library/Homebrew/formulary.rb:74:in `klass'
/home/admin1/.linuxbrew/Library/Homebrew/formulary.rb:70:in `get_formula'
/home/admin1/.linuxbrew/Library/Homebrew/formulary.rb:207:in `factory'
/home/admin1/.linuxbrew/Library/Homebrew/dependency.rb:32:in `to_formula'
/home/admin1/.linuxbrew/Library/Homebrew/dependency.rb:38:in `installed?'
/home/admin1/.linuxbrew/Library/Homebrew/build.rb:52:in `block in expand_reqs'
/home/admin1/.linuxbrew/Library/Homebrew/requirement.rb:215:in `block in prune?'
/home/admin1/.linuxbrew/Library/Homebrew/requirement.rb:213:in `catch'
/home/admin1/.linuxbrew/Library/Homebrew/requirement.rb:213:in `prune?'
/home/admin1/.linuxbrew/Library/Homebrew/requirement.rb:201:in `block (2 levels) in expand'
/usr/lib/ruby/2.3.0/set.rb:306:in `each_key'
/usr/lib/ruby/2.3.0/set.rb:306:in `each'
/home/admin1/.linuxbrew/Library/Homebrew/dependencies.rb:68:in `each'
/home/admin1/.linuxbrew/Library/Homebrew/requirement.rb:200:in `block in expand'
/home/admin1/.linuxbrew/Library/Homebrew/requirement.rb:199:in `each'
/home/admin1/.linuxbrew/Library/Homebrew/requirement.rb:199:in `expand'
/home/admin1/.linuxbrew/Library/Homebrew/formula.rb:1229:in `recursive_requirements'
/home/admin1/.linuxbrew/Library/Homebrew/build.rb:46:in `expand_reqs'
/home/admin1/.linuxbrew/Library/Homebrew/build.rb:27:in `initialize'
/home/admin1/.linuxbrew/Library/Homebrew/build.rb:176:in `new'
/home/admin1/.linuxbrew/Library/Homebrew/build.rb:176:in `<main>'
```

**Comment by sjackman** [comment]
Please enclose copy-and-paste blocks in triple back ticks.
See https://help.github.com/articles/basic-writing-and-formatting-syntax/#quoting-code

**Comment by sjackman** [comment]
Try…
```
brew update
brew install python3
```
