### ISSUE TITLE
getting this issue while trying to install tesseract

### ISSUE THREAD

**Issue by neelkadia-zz** [Linuxbrew/brew#425]
**brew install tesseract**
```
Error: undefined method `rebuild' for #<BottleSpecification:0x0000000204de48>
Please report this bug:
    https://github.com/Linuxbrew/linuxbrew/blob/master/share/doc/homebrew/Troubleshooting.md#troubleshooting
/home/kadia/.linuxbrew/Library/Taps/homebrew/homebrew-core/Formula/autoconf.rb:10:in `block in <class:Autoconf>'
/home/kadia/.linuxbrew/Library/Homebrew/software_spec.rb:91:in `instance_eval'
/home/kadia/.linuxbrew/Library/Homebrew/software_spec.rb:91:in `bottle'
/home/kadia/.linuxbrew/Library/Homebrew/formula.rb:1729:in `bottle'
/home/kadia/.linuxbrew/Library/Taps/homebrew/homebrew-core/Formula/autoconf.rb:8:in `<class:Autoconf>'
/home/kadia/.linuxbrew/Library/Taps/homebrew/homebrew-core/Formula/autoconf.rb:1:in `load_formula'
/home/kadia/.linuxbrew/Library/Homebrew/formulary.rb:21:in `module_eval'
/home/kadia/.linuxbrew/Library/Homebrew/formulary.rb:21:in `load_formula'
/home/kadia/.linuxbrew/Library/Homebrew/formulary.rb:34:in `load_formula_from_path'
/home/kadia/.linuxbrew/Library/Homebrew/formulary.rb:83:in `load_file'
/home/kadia/.linuxbrew/Library/Homebrew/formulary.rb:74:in `klass'
/home/kadia/.linuxbrew/Library/Homebrew/formulary.rb:70:in `get_formula'
/home/kadia/.linuxbrew/Library/Homebrew/formulary.rb:207:in `factory'
/home/kadia/.linuxbrew/Library/Homebrew/dependency.rb:32:in `to_formula'
/home/kadia/.linuxbrew/Library/Homebrew/dependency.rb:93:in `block in expand'
/home/kadia/.linuxbrew/Library/Homebrew/dependencies.rb:9:in `each'
/home/kadia/.linuxbrew/Library/Homebrew/dependencies.rb:9:in `each'
/home/kadia/.linuxbrew/Library/Homebrew/dependency.rb:80:in `expand'
/home/kadia/.linuxbrew/Library/Homebrew/formula.rb:1223:in `recursive_dependencies'
/home/kadia/.linuxbrew/Library/Homebrew/requirement.rb:196:in `expand'
/home/kadia/.linuxbrew/Library/Homebrew/formula.rb:1229:in `recursive_requirements'
/home/kadia/.linuxbrew/Library/Homebrew/formula_installer.rb:313:in `expand_requirements'
/home/kadia/.linuxbrew/Library/Homebrew/formula_installer.rb:263:in `compute_dependencies'
/home/kadia/.linuxbrew/Library/Homebrew/formula_installer.rb:130:in `verify_deps_exist'
/home/kadia/.linuxbrew/Library/Homebrew/formula_installer.rb:123:in `prelude'
/home/kadia/.linuxbrew/Library/Homebrew/cmd/install.rb:231:in `install_formula'
/home/kadia/.linuxbrew/Library/Homebrew/cmd/install.rb:93:in `block in install'
/home/kadia/.linuxbrew/Library/Homebrew/cmd/install.rb:93:in `each'
/home/kadia/.linuxbrew/Library/Homebrew/cmd/install.rb:93:in `install'
/home/kadia/.linuxbrew/Library/brew.rb:84:in `<main>'
```

**Comment by bw-yuhogg** [comment]
Can you try running `brew update` twice, then attempting the install again?

If that doesn't work, please provide the output of `brew config`, `brew doctor`, and `brew gist-logs autoconf`.

Also, when pasting stack traces on GitHub, please enclose them in triple-backticks (\`\`\` on either end) or else they can be hard to read. I've updated your comment to do this already.

Thanks!
