### ISSUE TITLE
cannot load such file -- json (LoadError)

### ISSUE THREAD

**Issue by zkanda** [Linuxbrew/brew#447]
Hello, I'm trying this on the new fedora 26 and I can't seem to install it, or rather when the installer tries to update brew.

Here's the log:

```
/usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- json (LoadError)
        from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/download_strategy.rb:1:in `<top (required)>'
        from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/resource.rb:1:in `<top (required)>'
        from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/extend/pathname.rb:2:in `<top (required)>'
        from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/global.rb:5:in `<top (required)>'
        from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/brew.rb:17:in `<main>'
Failed during: /home/linuxbrew/.linuxbrew/bin/brew update --force
```

**Comment by sjackman** [comment]
Please report the output of
```
brew update
which -a ruby
ruby --version
brew install homebrew/portable/portable-ruby
```

**Comment by zkanda** [comment]
Here's the output of those commands.

```
○ → brew update
Already up-to-date.
○ → which -a ruby
/usr/bin/ruby

○ → ruby --version
ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-linux]
○ → brew install homebrew/portable/portable-ruby
/usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- json (LoadError)
        from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/download_strategy.rb:1:in `<top (required)>'
        from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/resource.rb:1:in `<top (required)>'
        from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/extend/pathname.rb:2:in `<top (required)>'
        from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/global.rb:5:in `<top (required)>'
        from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/brew.rb:17:in `<main>'
```

**Comment by sjackman** [comment]
Please report the output of `brew config`
If you're familiar with your host's package manager, try installing the package that provides the file`json.rb`. On Ubuntu for example…
```sh
sudo apt-get install libruby2.4
```

**Comment by zkanda** [comment]
That did it, for some reason Fedora remove the json from standard ruby installation, I think it was included before(it's documented here too: https://developer.fedoraproject.org/tech/languages/ruby/ruby-installation.html).

Anyhow, here's how to solve it:

```
sudo dnf install rubygem-json 
```

**Comment by sjackman** [comment]
Thanks! That's helpful, Zakatell. Glad to hear that you got it working.
