### ISSUE TITLE
openssl upgrade/reinstall fails when using brewed Ruby

### ISSUE THREAD

**Issue by DoomHammer** [Linuxbrew/brew#47]
Seems there is a lot of work before a truly Standalone Linuxbrew installation would be possible, but we're slowly getting there :)

Error log:

```
brew reinstall openssl
==> Reinstalling openssl
/home/doomhammer/.linuxbrew/Cellar/ruby/2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require': libcrypto.so.1.0.0: cannot open shared object file: No such file or directory - /home/doomhammer/.linuxbrew/Cellar/ruby/2.3.1/lib/ruby/2.3.0/x86_64-linux/digest/md5.so (LoadError)
        from /home/doomhammer/.linuxbrew/Cellar/ruby/2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /home/doomhammer/.linuxbrew/Library/Homebrew/formulary.rb:1:in `<top (required)>'
        from /home/doomhammer/.linuxbrew/Cellar/ruby/2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /home/doomhammer/.linuxbrew/Cellar/ruby/2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /home/doomhammer/.linuxbrew/Library/Homebrew/formula.rb:8:in `<top (required)>'
        from /home/doomhammer/.linuxbrew/Cellar/ruby/2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /home/doomhammer/.linuxbrew/Cellar/ruby/2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /home/doomhammer/.linuxbrew/Library/Homebrew/extend/ENV/shared.rb:1:in `<top (required)>'
        from /home/doomhammer/.linuxbrew/Cellar/ruby/2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /home/doomhammer/.linuxbrew/Cellar/ruby/2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /home/doomhammer/.linuxbrew/Library/Homebrew/extend/ENV.rb:2:in `<top (required)>'
        from /home/doomhammer/.linuxbrew/Cellar/ruby/2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /home/doomhammer/.linuxbrew/Cellar/ruby/2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /home/doomhammer/.linuxbrew/Library/Homebrew/build.rb:10:in `<main>'
Error: Suspicious failure
```

**Comment by sjackman** [comment]
A workaround for this issue is:

``` sh
LD_LIBRARY_PATH=`brew --prefix openssl`/lib brew upgrade openssl
```

**Comment by DoomHammer** [comment]
See also: #304
