### ISSUE TITLE
php72: error info:Error: uninitialized constant AbstractPhp::MacOS

### ISSUE THREAD

**Issue by NicholasChan1025** [Linuxbrew/brew#585]
```
error info:Error: uninitialized constant AbstractPhp::MacOS
/home/sin/.linuxbrew/Library/Taps/homebrew/homebrew-php/Abstract/abstract-php.rb:31:in `init'
/home/sin/.linuxbrew/Library/Taps/homebrew/homebrew-php/Formula/php72.rb:4:in `<class:Php72>'
/home/sin/.linuxbrew/Library/Taps/homebrew/homebrew-php/Formula/php72.rb:3:in `load_formula'
/home/sin/.linuxbrew/Library/Homebrew/formulary.rb:27:in `module_eval'
/home/sin/.linuxbrew/Library/Homebrew/formulary.rb:27:in `load_formula'
/home/sin/.linuxbrew/Library/Homebrew/formulary.rb:47:in `load_formula_from_path'
/home/sin/.linuxbrew/Library/Homebrew/formulary.rb:102:in `load_file'
/home/sin/.linuxbrew/Library/Homebrew/formulary.rb:93:in `klass'
/home/sin/.linuxbrew/Library/Homebrew/formulary.rb:89:in `get_formula'
/home/sin/.linuxbrew/Library/Homebrew/formulary.rb:280:in `factory'
/home/sin/.linuxbrew/Library/Homebrew/formulary.rb:453:in `find_with_priority'
/home/sin/.linuxbrew/Library/Homebrew/extend/ARGV.rb:47:in `block in formulae'
/home/sin/.linuxbrew/Library/Homebrew/extend/ARGV.rb:43:in `map'
/home/sin/.linuxbrew/Library/Homebrew/extend/ARGV.rb:43:in `formulae'
/home/sin/.linuxbrew/Library/Homebrew/cmd/install.rb:110:in `install'
/home/sin/.linuxbrew/Library/Homebrew/brew.rb:100:in `<main>'
```

**Comment by sjackman** [comment]
Please enclose copy-and-paste blocks in triple back ticks.
See https://help.github.com/articles/basic-writing-and-formatting-syntax/#quoting-code

**Comment by sjackman** [comment]
This issue was moved to Linuxbrew/homebrew-core#5873
