### ISSUE TITLE
Crash when curl is not installed

### ISSUE THREAD

**Issue by bukzor** [Linuxbrew/brew#640]
This occurred during my Android porting work, but I don't think it's really caused by that.

```
Error: no implicit conversion of nil into String
Please report this bug:
  https://github.com/Linuxbrew/brew/wiki/troubleshooting
/data/data/com.termux/files/home/prefix/brew/Library/Homebrew/utils/curl.rb:9:in `initialize'
/data/data/com.termux/files/home/prefix/brew/Library/Homebrew/utils/curl.rb:9:in `Pathname'
/data/data/com.termux/files/home/prefix/brew/Library/Homebrew/utils/curl.rb:9:in `block in curl_executable'
/data/data/com.termux/files/home/prefix/brew/Library/Homebrew/utils/curl.rb:9:in `map'
/data/data/com.termux/files/home/prefix/brew/Library/Homebrew/utils/curl.rb:9:in `curl_executable'
/data/data/com.termux/files/home/prefix/brew/Library/Homebrew/utils/curl.rb:16:in `curl_args'
/data/data/com.termux/files/home/prefix/brew/Library/Homebrew/utils/github.rb:133:in `open'
/data/data/com.termux/files/home/prefix/brew/Library/Homebrew/utils/github.rb:258:in `private_repo?'
/data/data/com.termux/files/home/prefix/brew/Library/Homebrew/tap.rb:555:in `read_or_set_private_config'
/data/data/com.termux/files/home/prefix/brew/Library/Homebrew/tap.rb:193:in `private?'
/data/data/com.termux/files/home/prefix/brew/Library/Homebrew/tap.rb:291:in `install'
/data/data/com.termux/files/home/prefix/brew/Library/Homebrew/cmd/tap.rb:52:in `tap'
/data/data/com.termux/files/home/prefix/brew/Library/Homebrew/brew.rb:100:in `<main>'
Error: Failure while executing: /data/data/com.termux/files/home/prefix/brew/bin/brew tap homebrew/core
```

**Comment by bukzor** [comment]
This improves the error message greatly:

```
$ git diff
diff --git a/Library/Homebrew/utils/curl.rb b/Library/Homebrew/utils/curl.rb
index 65edd85df..b4e3b2429 100644
--- a/Library/Homebrew/utils/curl.rb
+++ b/Library/Homebrew/utils/curl.rb
@@ -6,7 +6,7 @@ def curl_executable
     ENV["HOMEBREW_CURL"],
     which("curl"),
     "/usr/bin/curl",
-  ].map { |c| Pathname(c) }.find(&:executable?)
+  ].reject(&:nil?).map { |c| Pathname(c) }.find(&:executable?)
   raise "curl is not executable" unless @curl
   @curl
 end

$ ./bin/brew tap --branch-okay homebrew/core
Connection to github.com closed by remote host. 102.00 KiB/s    
fatal: The remote end hung up unexpectedly
remote: Total 4716 (delta 47), reused 365 (delta 15), pack-reused 0
Receiving objects: 100% (4716/4716), 3.97 MiB | 95.00 KiB/s, done.
Resolving deltas: 100% (47/47), done.
Checking out files: 100% (4733/4733), done.
Tapped 4508 formulae (4,758 files, 12.4MB)
Error: curl is not executable
```

**Comment by sjackman** [comment]
Looks good to me. Please send this PR upstream to Homebrew/brew. I'd suggest also changing the error message, perhaps `brew requires curl, which is not available`

**Comment by sjackman** [comment]
Thanks for fixing this bug, Buck! ❤️
I appreciate your contribution to Linuxbrew very much! 🏅

Fixed by https://github.com/Homebrew/brew/pull/3941

**Comment by bukzor** [comment]
I got a medal! :raised_hands:

**Comment by sjackman** [comment]
Your fix will make it into Linuxbrew once PR https://github.com/Linuxbrew/brew/pull/661 is merged.
