### ISSUE TITLE
Uninitialized constant OS::Mac::CLT

### ISSUE THREAD

**Issue by TiZ-HugLife** [Linuxbrew/brew#652]
# Please fill out the issue checklist below, and provide all of the requested information.

# Please always follow these steps:
- [x] ran a `brew` command and reproduced the problem with multiple formulae? If it's a problem with a single, official formula please file this issue at Linuxbrew/homebrew-core: https://github.com/Linuxbrew/homebrew-core/issues/new. If it's a tap problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why): Install llvm@5 bottle made for my /xusr/linuxbrew cellar location, created on my home server. I can't build it at work; llvm chokes it to death. So I build a bottle on my server for both my laptop and my work box.
- What happened (include command output): Immediate crash.
- What you expected to happen: Installs the bottle from the given file.
- Step-by-step reproduction instructions (by running `brew` commands): `brew install --force-bottle -f /tmp/llvm@5-5.0.1.x86_64_linux.bottle.1.tar.gz` Force bottle is necessary because there's no way to tell it that the bottle is okay for its cellar without modifying the formula.

Output:
```
TiZLappy:tmp$ brew install --force-bottle -f /tmp/llvm@5-5.0.1.x86_64_linux.bottle.1.tar.gz
Error: uninitialized constant OS::Mac::CLT
Please report this bug:
  https://github.com/Linuxbrew/brew/wiki/troubleshooting
/xusr/linuxbrew/Library/Taps/homebrew/homebrew-core/Formula/python@2.rb:82:in `block (2 levels) in <class:PythonAT2>'
/xusr/linuxbrew/Library/Homebrew/formula_installer.rb:121:in `install_bottle_for?'
/xusr/linuxbrew/Library/Homebrew/formula_installer.rb:500:in `block in expand_dependencies'
/xusr/linuxbrew/Library/Homebrew/dependency.rb:109:in `block in action'
/xusr/linuxbrew/Library/Homebrew/dependency.rb:107:in `catch'
/xusr/linuxbrew/Library/Homebrew/dependency.rb:107:in `action'
/xusr/linuxbrew/Library/Homebrew/dependency.rb:86:in `block in expand'
/xusr/linuxbrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3.0/delegate.rb:341:in `each'
/xusr/linuxbrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3.0/delegate.rb:341:in `block in delegating_block'
/xusr/linuxbrew/Library/Homebrew/dependency.rb:83:in `expand'
/xusr/linuxbrew/Library/Homebrew/dependency.rb:91:in `block in expand'
/xusr/linuxbrew/Library/Homebrew/dependency.rb:83:in `each'
/xusr/linuxbrew/Library/Homebrew/dependency.rb:83:in `expand'
/xusr/linuxbrew/Library/Homebrew/formula_installer.rb:494:in `expand_dependencies'
/xusr/linuxbrew/Library/Homebrew/formula_installer.rb:381:in `compute_dependencies'
/xusr/linuxbrew/Library/Homebrew/formula_installer.rb:136:in `verify_deps_exist'
/xusr/linuxbrew/Library/Homebrew/formula_installer.rb:129:in `prelude'
/xusr/linuxbrew/Library/Homebrew/cmd/install.rb:378:in `install_formula'
/xusr/linuxbrew/Library/Homebrew/cmd/install.rb:232:in `block in install'
/xusr/linuxbrew/Library/Homebrew/cmd/install.rb:230:in `each'
/xusr/linuxbrew/Library/Homebrew/cmd/install.rb:230:in `install'
/xusr/linuxbrew/Library/Homebrew/brew.rb:100:in `<main>'
```

brew config:
```
TiZLappy:tmp$ brew config
HOMEBREW_VERSION: 1.5.8-7-gf9b1831
ORIGIN: https://github.com/Linuxbrew/brew.git
HEAD: f9b183178562e7546d5a41dfc0f28a9b75d824df
Last commit: 2 hours ago
Core tap ORIGIN: https://github.com/Linuxbrew/homebrew-core
Core tap HEAD: 9e1307ac68e85dca3905bc11d3e50d30016f59e7
Core tap last commit: 5 hours ago
HOMEBREW_PREFIX: /xusr/linuxbrew
HOMEBREW_REPOSITORY: /xusr/linuxbrew
HOMEBREW_CELLAR: /xusr/linuxbrew/Cellar
HOMEBREW_CACHE: /xusr/linuxbrew/.cache/Homebrew
HOMEBREW_CELLAR: /xusr/linuxbrew/Cellar
HOMEBREW_DEV_CMD_RUN: 1
HOMEBREW_PREFIX: /xusr/linuxbrew
HOMEBREW_REPOSITORY: /xusr/linuxbrew
HOMEBREW_RUBY_WARNINGS: -W0
CPU: octa-core 64-bit skylake
Homebrew Ruby: 2.3.3 => /xusr/linuxbrew/Library/Homebrew/vendor/portable-ruby/2.3.3/bin/ruby
Clang: N/A
Git: 2.7.4 => /usr/bin/git
Curl: 7.47.0 => /usr/bin/curl
Perl: /xusr/linuxbrew/bin/perl => /xusr/linuxbrew/Cellar/perl/5.26.1_1/bin/perl
Python: /xusr/linuxbrew/opt/python/libexec/bin/python => /xusr/linuxbrew/Cellar/python/3.6.4_5/bin/python3.6
Ruby: /xusr/linuxbrew/bin/ruby => /xusr/linuxbrew/Cellar/ruby/2.5.0_2/bin/ruby
Java: N/A
Kernel: Linux 4.15.10-xanmod11 x86_64 GNU/Linux
OS: Ubuntu 16.04.4 LTS (xenial)
Host glibc: 2.23
/usr/bin/gcc: 5.4.0
glibc: N/A
gcc: 5.5.0_3
xorg: 20170115_1
```

brew doctor. libiniparser is from an old manual installation of cava's X fork.
```
TiZLappy:tmp$ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Unbrewed .la files were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected .la files:
  /usr/local/lib/libiniparser.la

Warning: Unbrewed static libraries were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected static libraries:
  /usr/local/lib/libiniparser.a
```

**Comment by sjackman** [comment]
Thanks for the bug report, Trent. This PR should resolve your issue, once it's merged. https://github.com/Linuxbrew/brew/pull/653

**Comment by sjackman** [comment]
I've merged PR #653. `brew update` should resolve your issue.

**Comment by TiZ-HugLife** [comment]
I really appreciate you getting to this so fast! But now I've got another problem...

```
WC130-TiZ:~$ brew install --force-bottle -f /tmp/llvm@5-5.0.1.x86_64_linux.bottle.1.tar.gz
[sudo] password for tiz: 
Error: undefined method `installed?' for OS::Mac::CLT:Module
Did you mean?  instance_of?
Please report this bug:
  https://github.com/Linuxbrew/brew/wiki/troubleshooting
/xusr/linuxbrew/Library/Taps/homebrew/homebrew-core/Formula/python@2.rb:82:in `block (2 levels) in <class:PythonAT2>'
/xusr/linuxbrew/Library/Homebrew/formula_installer.rb:121:in `install_bottle_for?'
/xusr/linuxbrew/Library/Homebrew/formula_installer.rb:500:in `block in expand_dependencies'
/xusr/linuxbrew/Library/Homebrew/dependency.rb:109:in `block in action'
/xusr/linuxbrew/Library/Homebrew/dependency.rb:107:in `catch'
/xusr/linuxbrew/Library/Homebrew/dependency.rb:107:in `action'
/xusr/linuxbrew/Library/Homebrew/dependency.rb:86:in `block in expand'
/xusr/linuxbrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3.0/delegate.rb:341:in `each'
/xusr/linuxbrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3.0/delegate.rb:341:in `block in delegating_block'
/xusr/linuxbrew/Library/Homebrew/dependency.rb:83:in `expand'
/xusr/linuxbrew/Library/Homebrew/dependency.rb:91:in `block in expand'
/xusr/linuxbrew/Library/Homebrew/dependency.rb:83:in `each'
/xusr/linuxbrew/Library/Homebrew/dependency.rb:83:in `expand'
/xusr/linuxbrew/Library/Homebrew/formula_installer.rb:494:in `expand_dependencies'
/xusr/linuxbrew/Library/Homebrew/formula_installer.rb:381:in `compute_dependencies'
/xusr/linuxbrew/Library/Homebrew/formula_installer.rb:136:in `verify_deps_exist'
/xusr/linuxbrew/Library/Homebrew/formula_installer.rb:129:in `prelude'
/xusr/linuxbrew/Library/Homebrew/cmd/install.rb:378:in `install_formula'
/xusr/linuxbrew/Library/Homebrew/cmd/install.rb:232:in `block in install'
/xusr/linuxbrew/Library/Homebrew/cmd/install.rb:230:in `each'
/xusr/linuxbrew/Library/Homebrew/cmd/install.rb:230:in `install'
/xusr/linuxbrew/Library/Homebrew/brew.rb:100:in `<main>'
```

**Comment by TiZ-HugLife** [comment]
Okay, my second issue was "fixed" by commenting out line 82 of python@2's formula. I don't think that's a real fix for you guys though. :P

EDIT: Scratch that, it ran into the same thing while installing the bottle itself:

```
==> Pouring llvm@5-5.0.1.x86_64_linux.bottle.1.tar.gz
Warning: llvm@5 dependency berkeley-db was built with a different C++ standard
library (libstdc++ from gcc-4.8). This may cause problems at runtime.
Error: undefined method `installed?' for OS::Mac::CLT:Module
Did you mean?  instance_of?
Please report this bug:
  https://github.com/Linuxbrew/brew/wiki/troubleshooting
/tmp/llvm@5-5.0.1.x86_64_linux.bottle.1.tar.gz:198:in `build_libcxx?'
/tmp/llvm@5-5.0.1.x86_64_linux.bottle.1.tar.gz:356:in `caveats'
/xusr/linuxbrew/Library/Homebrew/caveats.rb:18:in `caveats'
/xusr/linuxbrew/Library/Homebrew/formula_installer.rb:609:in `caveats'
/xusr/linuxbrew/Library/Homebrew/formula_installer.rb:635:in `finish'
/xusr/linuxbrew/Library/Homebrew/cmd/install.rb:380:in `install_formula'
/xusr/linuxbrew/Library/Homebrew/cmd/install.rb:232:in `block in install'
/xusr/linuxbrew/Library/Homebrew/cmd/install.rb:230:in `each'
/xusr/linuxbrew/Library/Homebrew/cmd/install.rb:230:in `install'
/xusr/linuxbrew/Library/Homebrew/brew.rb:100:in `<main>'
```

Should I open a new issue for this?

**Comment by sjackman** [comment]
Should be fixed now by PR https://github.com/Linuxbrew/brew/pull/655
