### ISSUE TITLE
installing ccm maven returns Error: undefined method `rebuild'

### ISSUE THREAD

**Issue by Elemino** [Linuxbrew/brew#680]
Hello,

Not sure if this could be of help, but here you go. :)

```
$  brew install ccm maven
Error: undefined method `rebuild' for #<BottleSpecification:0x0055a3395d2528>
Please report this bug:
  https://github.com/Linuxbrew/linuxbrew/blob/master/share/doc/homebrew/Troubleshooting.md#troubleshooting
/home/user/.linuxbrew/Library/Taps/homebrew/homebrew-core/Formula/python@2.rb:10:in `block in <class:PythonAT2>'
/home/user/.linuxbrew/Library/Homebrew/software_spec.rb:91:in `instance_eval'
/home/user/.linuxbrew/Library/Homebrew/software_spec.rb:91:in `bottle'
/home/user/.linuxbrew/Library/Homebrew/formula.rb:1729:in `bottle'
/home/user/.linuxbrew/Library/Taps/homebrew/homebrew-core/Formula/python@2.rb:9:in `<class:PythonAT2>'
/home/user/.linuxbrew/Library/Taps/homebrew/homebrew-core/Formula/python@2.rb:1:in `load_formula'
/home/user/.linuxbrew/Library/Homebrew/formulary.rb:21:in `module_eval'
/home/user/.linuxbrew/Library/Homebrew/formulary.rb:21:in `load_formula'
/home/user/.linuxbrew/Library/Homebrew/formulary.rb:34:in `load_formula_from_path'
/home/user/.linuxbrew/Library/Homebrew/formulary.rb:83:in `load_file'
/home/user/.linuxbrew/Library/Homebrew/formulary.rb:74:in `klass'
/home/user/.linuxbrew/Library/Homebrew/formulary.rb:70:in `get_formula'
/home/user/.linuxbrew/Library/Homebrew/formulary.rb:207:in `factory'
/home/user/.linuxbrew/Library/Homebrew/dependency.rb:32:in `to_formula'
/home/user/.linuxbrew/Library/Homebrew/dependency.rb:93:in `block in expand'
/home/user/.linuxbrew/Library/Homebrew/dependencies.rb:9:in `each'
/home/user/.linuxbrew/Library/Homebrew/dependencies.rb:9:in `each'
/home/user/.linuxbrew/Library/Homebrew/dependency.rb:80:in `expand'
/home/user/.linuxbrew/Library/Homebrew/formula.rb:1223:in `recursive_dependencies'
/home/user/.linuxbrew/Library/Homebrew/requirement.rb:196:in `expand'
/home/user/.linuxbrew/Library/Homebrew/formula.rb:1229:in `recursive_requirements'
/home/user/.linuxbrew/Library/Homebrew/formula_installer.rb:313:in `expand_requirements'
/home/user/.linuxbrew/Library/Homebrew/formula_installer.rb:263:in `compute_dependencies'
/home/user/.linuxbrew/Library/Homebrew/formula_installer.rb:130:in `verify_deps_exist'
/home/user/.linuxbrew/Library/Homebrew/formula_installer.rb:123:in `prelude'
/home/user/.linuxbrew/Library/Homebrew/cmd/install.rb:231:in `install_formula'
/home/user/.linuxbrew/Library/Homebrew/cmd/install.rb:93:in `block in install'
/home/user/.linuxbrew/Library/Homebrew/cmd/install.rb:93:in `each'
/home/user/.linuxbrew/Library/Homebrew/cmd/install.rb:93:in `install'
/home/user/.linuxbrew/Library/brew.rb:84:in `<main>'  ```

**Comment by Elemino** [comment]
```

$ brew install maven
Error: undefined method `version_scheme' for Formulary::FormulaNamespace1e4df11cef40743188d1fa56434a7390::Jdk:Class
Please report this bug:
    https://github.com/Linuxbrew/linuxbrew/blob/master/share/doc/homebrew/Troubleshooting.md#troubleshooting
/home/user/.linuxbrew/Library/Taps/homebrew/homebrew-core/Formula/jdk.rb:13:in `<class:Jdk>'
/home/user/.linuxbrew/Library/Taps/homebrew/homebrew-core/Formula/jdk.rb:7:in `load_formula'
/home/user/.linuxbrew/Library/Homebrew/formulary.rb:21:in `module_eval'
/home/user/.linuxbrew/Library/Homebrew/formulary.rb:21:in `load_formula'
/home/user/.linuxbrew/Library/Homebrew/formulary.rb:34:in `load_formula_from_path'
/home/user/.linuxbrew/Library/Homebrew/formulary.rb:83:in `load_file'
/home/user/.linuxbrew/Library/Homebrew/formulary.rb:74:in `klass'
/home/user/.linuxbrew/Library/Homebrew/formulary.rb:70:in `get_formula'
/home/user/.linuxbrew/Library/Homebrew/formulary.rb:207:in `factory'
/home/user/.linuxbrew/Library/Homebrew/dependency.rb:32:in `to_formula'
/home/user/.linuxbrew/Library/Homebrew/formula_installer.rb:323:in `block in expand_requirements'
/home/user/.linuxbrew/Library/Homebrew/requirement.rb:215:in `block in prune?'
/home/user/.linuxbrew/Library/Homebrew/requirement.rb:213:in `catch'
/home/user/.linuxbrew/Library/Homebrew/requirement.rb:213:in `prune?'
/home/user/.linuxbrew/Library/Homebrew/requirement.rb:201:in `block (2 levels) in expand'
/home/user/.rbenv/versions/2.3.1/lib/ruby/2.3.0/set.rb:306:in `each_key'
/home/user/.rbenv/versions/2.3.1/lib/ruby/2.3.0/set.rb:306:in `each'
/home/user/.linuxbrew/Library/Homebrew/dependencies.rb:68:in `each'
/home/user/.linuxbrew/Library/Homebrew/requirement.rb:200:in `block in expand'
/home/user/.linuxbrew/Library/Homebrew/requirement.rb:199:in `each'
/home/user/.linuxbrew/Library/Homebrew/requirement.rb:199:in `expand'
/home/user/.linuxbrew/Library/Homebrew/formula.rb:1229:in `recursive_requirements'
/home/user/.linuxbrew/Library/Homebrew/formula_installer.rb:313:in `expand_requirements'
/home/user/.linuxbrew/Library/Homebrew/formula_installer.rb:263:in `compute_dependencies'
/home/user/.linuxbrew/Library/Homebrew/formula_installer.rb:130:in `verify_deps_exist'
/home/user/.linuxbrew/Library/Homebrew/formula_installer.rb:123:in `prelude'
/home/user/.linuxbrew/Library/Homebrew/cmd/install.rb:231:in `install_formula'
/home/user/.linuxbrew/Library/Homebrew/cmd/install.rb:93:in `block in install'
/home/user/.linuxbrew/Library/Homebrew/cmd/install.rb:93:in `each'
/home/user/.linuxbrew/Library/Homebrew/cmd/install.rb:93:in `install'
/home/user/.linuxbrew/Library/brew.rb:84:in `<main>'
```

**Comment by iMichka** [comment]
Hi. Please report this here: https://github.com/Linuxbrew/homebrew-core

And fill out the issue template. Also, it would be good to know if the bug is coming from `maven` or `ccm`.

**Comment by sjackman** [comment]
Please enclose copy-and-paste blocks in triple back ticks.
See https://help.github.com/articles/basic-writing-and-formatting-syntax/#quoting-code

**Comment by danielcompton** [comment]
I got this error too, it went away after running `brew update`.
