### ISSUE TITLE
brew tests fails with TabTests#test_defaults reporting the wrong compiler

### ISSUE THREAD

**Issue by bw-yuhogg** [Linuxbrew/brew#69]
# Please follow the general troubleshooting steps first:
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [x] If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`?
### Bug reports:

`brew tests` fails with the following error.

```
  1) Failure:
TabTests#test_defaults [/home/bob/.linuxbrew/Library/Homebrew/test/test_tab.rb:35]:
--- expected
+++ actual
@@ -1 +1 @@
-:clang
+:gcc


853 runs, 2098 assertions, 1 failures, 0 errors, 12 skips

You have skipped tests. Run with --verbose for details.
rake aborted!
Command failed with status (1): [ruby -I"lib:/home/bob/.linuxbrew/Library/Homebrew/test" -I"/home/bob/.linuxbrew/Library/Homebrew/test/vendor/bundle/ruby/2.3.0/gems/rake-10.5.0/lib" "/home/bob/.linuxbrew/Library/Homebrew/test/vendor/bundle/ruby/2.3.0/gems/rake-10.5.0/lib/rake/rake_test_loader.rb" "/home/bob/.linuxbrew/Library/Homebrew/test/test_dependency_collector.rb" "/home/bob/.linuxbrew/Library/Homebrew/test/test_commands.rb" "/home/bob/.linuxbrew/Library/Homebrew/test/test_diagnostic.rb" "/home/bob/.linuxbrew/Library/Homebrew/test/test_options.rb" "/home/bob/.linuxbrew/Library/Homebrew/test/test_compiler_selector.rb" "/home/bob/.linuxbrew/Library/Homebrew/test/test_hardware.rb" "/home/bob/.linuxbrew/Library/Homebrew/test/test_formula_validation.rb" "/home/bob/.linuxbrew/Library/Homebrew/test/test_pathname.rb" "/home/bob/.linuxbrew/Library/Homebrew/test/test_build_environment.rb" "/home/bob/.linuxbrew/Library/Homebrew/test/test_version_subclasses.rb" "/home/bob/.linuxbrew/Library/Homebrew/test/test_inreplace.rb" "/home/bob/.linuxbrew/Library/Homebrew/test/test_formula_installer.rb" "/home/bob/.linuxbrew/Library/Homebrew/test/test_keg.rb" "/home/bob/.linuxbrew/Library/Homebrew/test/test_checksum.rb" "/home/bob/.linuxbrew/Library/Homebrew/test/test_mach.rb" "/home/bob/.linuxbrew/Library/Homebrew/test/test_cleanup.rb" "/home/bob/.linuxbrew/Library/Homebrew/test/test_checksum_verification.rb" "/home/bob/.linuxbrew/Library/Homebrew/test/test_formula_pin.rb" "/home/bob/.linuxbrew/Library/Homebrew/test/test_mpi_requirement.rb" "/home/bob/.linuxbrew/Library/Homebrew/test/test_tap.rb" "/home/bob/.linuxbrew/Library/Homebrew/test/test_bottle_filename.rb" "/home/bob/.linuxbrew/Library/Homebrew/test/test_download_strategies.rb" "/home/bob/.linuxbrew/Library/Homebrew/test/test_patching.rb" "/home/bob/.linuxbrew/Library/Homebrew/test/test_cmd_info.rb" "/home/bob/.linuxbrew/Library/Homebrew/test/test_integration_cmds.rb" "/home/bob/.linuxbrew/Library/Homebrew/test/test_utils.rb" "/home/bob/.linuxbrew/Library/Homebrew/test/test_x11_requirement.rb" "/home/bob/.linuxbrew/Library/Homebrew/test/test_bottle_hooks.rb" "/home/bob/.linuxbrew/Library/Homebrew/test/test_stdlib.rb" "/home/bob/.linuxbrew/Library/Homebrew/test/test_language_module_requirement.rb" "/home/bob/.linuxbrew/Library/Homebrew/test/test_patch.rb" "/home/bob/.linuxbrew/Library/Homebrew/test/test_dependency.rb" "/home/bob/.linuxbrew/Library/Homebrew/test/test_formula_installer_bottle.rb" "/home/bob/.linuxbrew/Library/Homebrew/test/test_pkg_version.rb" "/home/bob/.linuxbrew/Library/Homebrew/test/test_formula_lock.rb" "/home/bob/.linuxbrew/Library/Homebrew/test/test_versions.rb" "/home/bob/.linuxbrew/Library/Homebrew/test/test_cleaner.rb" "/home/bob/.linuxbrew/Library/Homebrew/test/test_json.rb" "/home/bob/.linuxbrew/Library/Homebrew/test/test_formulary.rb" "/home/bob/.linuxbrew/Library/Homebrew/test/test_formula_support.rb" "/home/bob/.linuxbrew/Library/Homebrew/test/test_sandbox.rb" "/home/bob/.linuxbrew/Library/Homebrew/test/test_dependencies.rb" "/home/bob/.linuxbrew/Library/Homebrew/test/test_exceptions.rb" "/home/bob/.linuxbrew/Library/Homebrew/test/test_bottle_collector.rb" "/home/bob/.linuxbrew/Library/Homebrew/test/test_caveats.rb" "/home/bob/.linuxbrew/Library/Homebrew/test/test_migrator.rb" "/home/bob/.linuxbrew/Library/Homebrew/test/test_update_report.rb" "/home/bob/.linuxbrew/Library/Homebrew/test/test_formula.rb" "/home/bob/.linuxbrew/Library/Homebrew/test/test_resource.rb" "/home/bob/.linuxbrew/Library/Homebrew/test/test_ARGV.rb" "/home/bob/.linuxbrew/Library/Homebrew/test/test_software_spec.rb" "/home/bob/.linuxbrew/Library/Homebrew/test/test_formula_spec_selection.rb" "/home/bob/.linuxbrew/Library/Homebrew/test/test_ENV.rb" "/home/bob/.linuxbrew/Library/Homebrew/test/test_cmd_audit.rb" "/home/bob/.linuxbrew/Library/Homebrew/test/test_string.rb" "/home/bob/.linuxbrew/Library/Homebrew/test/test_dependency_expansion.rb" "/home/bob/.linuxbrew/Library/Homebrew/test/test_descriptions.rb" "/home/bob/.linuxbrew/Library/Homebrew/test/test_tab.rb" "/home/bob/.linuxbrew/Library/Homebrew/test/test_bash.rb" "/home/bob/.linuxbrew/Library/Homebrew/test/test_compiler_failure.rb" "/home/bob/.linuxbrew/Library/Homebrew/test/test_requirement.rb" "/home/bob/.linuxbrew/Library/Homebrew/test/test_blacklist.rb" "/home/bob/.linuxbrew/Library/Homebrew/test/test_build_options.rb" "/home/bob/.linuxbrew/Library/Homebrew/test/test_language_go.rb" "/home/bob/.linuxbrew/Library/Homebrew/test/test_bottle_tag.rb" ]
/home/bob/.linuxbrew/Library/Homebrew/test/vendor/bundle/ruby/2.3.0/gems/rake-10.5.0/lib/rake/testtask.rb:109:in `block (3 levels) in define'
/home/bob/.linuxbrew/Library/Homebrew/test/vendor/bundle/ruby/2.3.0/gems/rake-10.5.0/lib/rake/file_utils.rb:57:in `sh'
/home/bob/.linuxbrew/Library/Homebrew/test/vendor/bundle/ruby/2.3.0/gems/rake-10.5.0/lib/rake/file_utils_ext.rb:37:in `sh'
/home/bob/.linuxbrew/Library/Homebrew/test/vendor/bundle/ruby/2.3.0/gems/rake-10.5.0/lib/rake/file_utils.rb:96:in `ruby'
/home/bob/.linuxbrew/Library/Homebrew/test/vendor/bundle/ruby/2.3.0/gems/rake-10.5.0/lib/rake/file_utils_ext.rb:37:in `ruby'
/home/bob/.linuxbrew/Library/Homebrew/test/vendor/bundle/ruby/2.3.0/gems/rake-10.5.0/lib/rake/testtask.rb:105:in `block (2 levels) in define'
/home/bob/.linuxbrew/Library/Homebrew/test/vendor/bundle/ruby/2.3.0/gems/rake-10.5.0/lib/rake/file_utils_ext.rb:58:in `verbose'
/home/bob/.linuxbrew/Library/Homebrew/test/vendor/bundle/ruby/2.3.0/gems/rake-10.5.0/lib/rake/testtask.rb:101:in `block in define'
/home/bob/.linuxbrew/Library/Homebrew/test/vendor/bundle/ruby/2.3.0/gems/rake-10.5.0/lib/rake/task.rb:240:in `block in execute'
/home/bob/.linuxbrew/Library/Homebrew/test/vendor/bundle/ruby/2.3.0/gems/rake-10.5.0/lib/rake/task.rb:235:in `each'
/home/bob/.linuxbrew/Library/Homebrew/test/vendor/bundle/ruby/2.3.0/gems/rake-10.5.0/lib/rake/task.rb:235:in `execute'
/home/bob/.linuxbrew/Library/Homebrew/test/vendor/bundle/ruby/2.3.0/gems/rake-10.5.0/lib/rake/task.rb:179:in `block in invoke_with_call_chain'
/home/bob/.linuxbrew/Cellar/ruby/2.3.1/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
/home/bob/.linuxbrew/Library/Homebrew/test/vendor/bundle/ruby/2.3.0/gems/rake-10.5.0/lib/rake/task.rb:172:in `invoke_with_call_chain'
/home/bob/.linuxbrew/Library/Homebrew/test/vendor/bundle/ruby/2.3.0/gems/rake-10.5.0/lib/rake/task.rb:165:in `invoke'
/home/bob/.linuxbrew/Library/Homebrew/test/vendor/bundle/ruby/2.3.0/gems/rake-10.5.0/lib/rake/application.rb:150:in `invoke_task'
/home/bob/.linuxbrew/Library/Homebrew/test/vendor/bundle/ruby/2.3.0/gems/rake-10.5.0/lib/rake/application.rb:106:in `block (2 levels) in top_level'
/home/bob/.linuxbrew/Library/Homebrew/test/vendor/bundle/ruby/2.3.0/gems/rake-10.5.0/lib/rake/application.rb:106:in `each'
/home/bob/.linuxbrew/Library/Homebrew/test/vendor/bundle/ruby/2.3.0/gems/rake-10.5.0/lib/rake/application.rb:106:in `block in top_level'
/home/bob/.linuxbrew/Library/Homebrew/test/vendor/bundle/ruby/2.3.0/gems/rake-10.5.0/lib/rake/application.rb:115:in `run_with_threads'
/home/bob/.linuxbrew/Library/Homebrew/test/vendor/bundle/ruby/2.3.0/gems/rake-10.5.0/lib/rake/application.rb:100:in `top_level'
/home/bob/.linuxbrew/Library/Homebrew/test/vendor/bundle/ruby/2.3.0/gems/rake-10.5.0/lib/rake/application.rb:78:in `block in run'
/home/bob/.linuxbrew/Library/Homebrew/test/vendor/bundle/ruby/2.3.0/gems/rake-10.5.0/lib/rake/application.rb:176:in `standard_exception_handling'
/home/bob/.linuxbrew/Library/Homebrew/test/vendor/bundle/ruby/2.3.0/gems/rake-10.5.0/lib/rake/application.rb:75:in `run'
/home/bob/.linuxbrew/Library/Homebrew/test/vendor/bundle/ruby/2.3.0/gems/rake-10.5.0/bin/rake:33:in `<top (required)>'
/home/bob/.linuxbrew/Library/Homebrew/test/vendor/bundle/ruby/2.3.0/bin/rake:23:in `load'
/home/bob/.linuxbrew/Library/Homebrew/test/vendor/bundle/ruby/2.3.0/bin/rake:23:in `<top (required)>'
/home/bob/.linuxbrew/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/cli/exec.rb:63:in `load'
/home/bob/.linuxbrew/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/cli/exec.rb:63:in `kernel_load'
/home/bob/.linuxbrew/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/cli/exec.rb:24:in `run'
/home/bob/.linuxbrew/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/cli.rb:304:in `exec'
/home/bob/.linuxbrew/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/home/bob/.linuxbrew/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/home/bob/.linuxbrew/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
/home/bob/.linuxbrew/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
/home/bob/.linuxbrew/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/cli.rb:11:in `start'
/home/bob/.linuxbrew/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/exe/bundle:27:in `block in <top (required)>'
/home/bob/.linuxbrew/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/friendly_errors.rb:98:in `with_friendly_errors'
/home/bob/.linuxbrew/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/exe/bundle:19:in `<top (required)>'
/home/bob/.gem/ruby/2.3.0/bin/bundle:23:in `load'
/home/bob/.gem/ruby/2.3.0/bin/bundle:23:in `<main>'
Tasks: TOP => test
```

**Comment by bw-yuhogg** [comment]
From the GCC formula:

```
# Create cc and c++ symlinks, unless they already exist
homebrew_bin = Pathname.new "#{HOMEBREW_PREFIX}/bin"
homebrew_bin.install_symlink "gcc" => "cc" unless (homebrew_bin/"cc").exist?
homebrew_bin.install_symlink "g++" => "c++" unless (homebrew_bin/"c++").exist?
```

I'm going to see if changing the default compiler in the test to GCC fixes this. The `unless exist` parts imply that it won't always be true, but it should certainly be more common than `clang`.

**Comment by bw-yuhogg** [comment]
Nope, doesn't cut it. There's more errors if I do that.

**Comment by bw-yuhogg** [comment]
The problem appears to be that DevelopmentTools doesn't recognize `hardened-cc` as GCC.
The symlink pattern basically goes like this:

``` bash
bob:/home/bob/.linuxbrew/Library/Homebrew * master % readlink /usr/bin/cc
/etc/alternatives/cc
bob:/home/bob/.linuxbrew/Library/Homebrew * master % readlink /etc/alternatives/cc                                                             
/usr/bin/gcc
bob:/home/bob/.linuxbrew/Library/Homebrew * master % readlink /usr/bin/gcc                                                                     
gcc-4.8
bob:/home/bob/.linuxbrew/Library/Homebrew * master % readlink /usr/bin/gcc-4.8                                                                 
hardened-cc
```

`/usr/bin/hardened-cc` is not a symlink, it's a Perl script.
