### ISSUE TITLE
Error: comparison of Version::FromURL with #<Class:0x....> failed

### ISSUE THREAD

**Issue by tudormaz** [Linuxbrew/brew#693]
# Please fill out the issue checklist below, and provide all of the requested information.

# Please always follow these steps:
- [x] ran a `brew` command and reproduced the problem with multiple formulae? If it's a problem with a single, official formula please file this issue at Linuxbrew/homebrew-core: https://github.com/Linuxbrew/homebrew-core/issues/new. If it's a tap problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew config` and `brew doctor` and included their output with your issue?
```
8a98af09a6cb:~$ brew config
HOMEBREW_VERSION: 1.6.1-43-g64d5cb5
ORIGIN: https://github.com/Linuxbrew/brew
HEAD: 64d5cb51032e4f303bea33d88d02cad0f7327d33
Last commit: 2 days ago
Core tap ORIGIN: https://github.com/Linuxbrew/homebrew-core
Core tap HEAD: 782bc2c17137de192e56f582589b94504c9cd19b
Core tap last commit: 3 hours ago
HOMEBREW_PREFIX: /home/linuxbrew/.linuxbrew
HOMEBREW_REPOSITORY: /home/linuxbrew/.linuxbrew/Homebrew
HOMEBREW_CELLAR: /home/linuxbrew/.linuxbrew/Cellar
HOMEBREW_CACHE: /home/linuxbrew/.cache/Homebrew
CPU: quad-core 64-bit 0x69e
Homebrew Ruby: 2.4.4 => /usr/bin/ruby
Clang: N/A
Git: 2.15.0 => /usr/bin/git
Curl: 7.58.0 => /usr/bin/curl
Java: N/A
Kernel: Linux 4.9.87-linuxkit-aufs x86_64 GNU/Linux
OS: N/A
Host glibc: N/A
/usr/bin/gcc: N/A
glibc: N/A
gcc: N/A
xorg: N/A
```

To help us debug your issue please explain:
- What you were trying to do (and why)
- What happened (include command output)
- What you expected to happen
- Step-by-step reproduction instructions (by running `brew` commands)

```
Error: comparison of Version::FromURL with #<Class:0x000055a3910dd0d8> failed
Please report this bug:
  https://github.com/Linuxbrew/brew/wiki/troubleshooting
/home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/glibc.rb:5:in `>='
/home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/glibc.rb:5:in `block in <class:BrewedGlibcNotOlderRequirement>'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/requirement.rb:56:in `instance_eval'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/requirement.rb:56:in `block in satisfied?'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/requirement.rb:180:in `yielder'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/requirement.rb:56:in `satisfied?'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula_installer.rb:445:in `block in expand_requirements'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/requirement.rb:210:in `block in prune?'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/requirement.rb:208:in `catch'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/requirement.rb:208:in `prune?'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/requirement.rb:199:in `block (2 levels) in expand'
/usr/lib/ruby/2.4.0/set.rb:324:in `each_key'
/usr/lib/ruby/2.4.0/set.rb:324:in `each'
/usr/lib/ruby/2.4.0/delegate.rb:341:in `block in delegating_block'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/requirement.rb:198:in `block in expand'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/requirement.rb:197:in `each'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/requirement.rb:197:in `expand'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula.rb:1486:in `recursive_requirements'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula_installer.rb:439:in `expand_requirements'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula_installer.rb:382:in `compute_dependencies'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula_installer.rb:137:in `verify_deps_exist'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula_installer.rb:130:in `prelude'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula_installer.rb:595:in `install_dependency'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula_installer.rb:559:in `block in install_dependencies'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula_installer.rb:559:in `each'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula_installer.rb:559:in `install_dependencies'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula_installer.rb:262:in `install'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/cmd/install.rb:399:in `install_formula'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/cmd/install.rb:245:in `block in install'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/cmd/install.rb:243:in `each'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/cmd/install.rb:243:in `install'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/brew.rb:101:in `<main>'
```

**Comment by sjackman** [comment]
Please surround copied-and-pasted logs with triple back ticks. See [GitHub Help / Quoting Code](https://help.github.com/articles/basic-writing-and-formatting-syntax/#quoting-code).

**Comment by sjackman** [comment]
Which distribution of Linux are you running on? Does it have a public Docker image that I can use to reproduce this issue?

**Comment by tudormaz** [comment]
@sjackman Hello. The docker image is landoop/fast-data-dev:cp4.0.0, which is running an Alpine Linux.
```
cat /etc/*-release
3.7.0
NAME="Alpine Linux"
ID=alpine
VERSION_ID=3.7.0
PRETTY_NAME="Alpine Linux v3.7"
HOME_URL="http://alpinelinux.org"
BUG_REPORT_URL="http://bugs.alpinelinux.org"
```

**Comment by sjackman** [comment]
@tudormaz Perhaps this Alpine Linux Dockerfile will be useful to you:
https://github.com/Linuxbrew/docker/blob/master/alpine/Dockerfile
It works with both Alpine Linux 3.6 and 3.7.
