### ISSUE TITLE
brew audit --strict: Error: empty

### ISSUE THREAD

**Issue by bw-yuhogg** [Linuxbrew/brew#71]
# Please follow the general troubleshooting steps first:
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [x] If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`?
### Bug reports:

Run `brew audit --strict` on any formula. It will fail and report

```
Error: empty
Please report this bug:
    https://github.com/Linuxbrew/brew/blob/master/share/doc/homebrew/Troubleshooting.md#troubleshooting
/home/bob/.linuxbrew/Library/Homebrew/utils/json.rb:12:in `rescue in load'
/home/bob/.linuxbrew/Library/Homebrew/utils/json.rb:10:in `load'
/home/bob/.linuxbrew/Library/Homebrew/cmd/style.rb:68:in `check_style_impl'
/home/bob/.linuxbrew/Library/Homebrew/cmd/style.rb:45:in `check_style_json'
/home/bob/.linuxbrew/Library/Homebrew/cmd/audit.rb:62:in `audit'
/home/bob/.linuxbrew/Library/brew.rb:87:in `<main>'
```

Note that a standard audit without any options works fine.

**Comment by sjackman** [comment]
Works for me:

```
$ brew audit --strict git
==> Installing or updating 'rubocop' gem
Fetching: parser-2.3.1.2.gem (100%)
Successfully installed parser-2.3.1.2
Fetching: rubocop-0.40.0.gem (100%)
Successfully installed rubocop-0.40.0
2 gems installed
git:
  * Use `system "#{bin}/git", "init"` instead of `system "#{bin}/git init"` 
  * Use `system "#{bin}/git", "status"` instead of `system "#{bin}/git status"` 
  * Use `system "#{bin}/git", "config", "user.email", "\"` instead of `system "#{bin}/git config user.email \"` 
  * Use `system "#{bin}/git", "config", "user.name", "\"` instead of `system "#{bin}/git config user.name \"` 
  * Use `system "#{bin}/git", "add", "foo"` instead of `system "#{bin}/git add foo"` 
  * Use `system "#{bin}/git", "commit", "-m", "foo"` instead of `system "#{bin}/git commit -m foo"` 
  * C: 162: col 12: Prefer `!expression.nil?` over `expression != nil`.
Error: 7 problems in 1 formula
```

`Vendor::OkJson.decode(str)` is failing. To debug, try:

```
$ brew irb <<<'Vendor::OkJson.decode("[123]")'
==> Interactive Homebrew Shell
Example commands available with: brew irb --examples
Switch to inspect mode.
Vendor::OkJson.decode("[123]")
[123]
```

https://github.com/Linuxbrew/brew/blob/master/Library/Homebrew/utils/json.rb#L10

``` ruby
    def load(str)
      Vendor::OkJson.decode(str)
    rescue Vendor::OkJson::Error => e
      raise Error, e.message
    end
```

**Comment by bw-yuhogg** [comment]
I did a `gem update` and now it works. Not sure what gives...

Closing, thanks for the assistance Shaun!

**Comment by sjackman** [comment]
No worries. Any time.
