### ISSUE TITLE
Cannot run any command after brew update

### ISSUE THREAD

**Issue by thedrow** [Linuxbrew/brew#716]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [x] ran a `brew` command and reproduced the problem with multiple formulae? If it's a problem with a single, official formula (not cask) please file this issue at Linuxbrew/homebrew-core: https://github.com/Linuxbrew/homebrew-core/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/caskroom/homebrew-cask/issues/new. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [ ] ran `brew doctor`, fixed all issues and can still reproduce the problem?
brew doctor produces the same exception I'm reporting.
- [x] ran `brew config` and `brew doctor` and included their output with your issue?
```
HOMEBREW_VERSION: 1.6.3-2-gdb20cf6
ORIGIN: https://github.com/Linuxbrew/brew
HEAD: db20cf6a67ed870c8264b375e8405898cc160484
Last commit: 11 days ago
Core tap ORIGIN: https://github.com/Linuxbrew/homebrew-core
Core tap HEAD: dc037ef165f57f62e127f39ec5423bbf4b10b3b2
Core tap last commit: 21 hours ago
HOMEBREW_PREFIX: /home/linuxbrew/.linuxbrew
HOMEBREW_REPOSITORY: /home/linuxbrew/.linuxbrew/Homebrew
HOMEBREW_CELLAR: /home/linuxbrew/.linuxbrew/Cellar
HOMEBREW_CACHE: /home/omer/.cache/Homebrew
HOMEBREW_DEV_CMD_RUN: 1
CPU: octa-core 64-bit 0x69e
Homebrew Ruby: 2.5.1 => /usr/bin/ruby2.5
Clang: 6.0 build 600
Git: 2.16.2 => /usr/bin/git
Curl: 7.58.0 => /usr/bin/curl
Java: N/A
Kernel: Linux 4.15.0-22-generic x86_64 GNU/Linux
OS: Ubuntu 18.04 LTS (bionic)
Host glibc: 2.27
/usr/bin/gcc: 7.3.0
glibc: N/A
gcc: 5.5.0_4
xorg: 20170115_1
```
brew config doesn't work.

To help us debug your issue please explain:
- What you were trying to do (and why): brew update
- What happened (include command output):
```
Error: 765: unexpected token at '{
  "adobe-air-sdk": "homebrew/cask",
  "android-ndk": "homebrew/cask",
  "android-platform-tools": "homebrew/cask",
  "android-sdk": "homebrew/cask",
  "app-engine-go-32": "homebrew/cask/google-cloud-sdk",
  "app-engine-go-64": "homebrew/cask/google-cloud-sdk",
  "auctex": "homebrew/tex",
  "avidemux": "homebrew/cask",
  "awsenv": "Luzifer/tools",
  "chromedriver": "homebrew/cask",
  "cloudfoundry-cli": "pivotal/tap",
  "cmucl": "homebrew/cask",
  "crystax-ndk": "homebrew/cask",
  "corelocationcli": "homebrew/cask",
  "dart": "dart-lang/dart",
  "dbt": "fishtown-analytics/dbt",
  "dwarf-fortress": "homebrew/cask",
  "geany": "homebrew/cask",
  "gimp": "homebrew/cask",
  "grads": "homebrew/cask",
  "gtkwave": "homebrew/cask",
  "helios": "spotify/public",
  "hexchat": "homebrew/cask",
  "horndis": "homebrew/cask",
  "inkscape": "homebrew/cask",
  "jsl": "homebrew/cask",
  "kdiff3": "homebrew/cask",
  "keybase": "homebrew/cask",
  "magit": "dunn/emacs",
  "meld": "homebrew/cask",
  "osxfuse": "homebrew/cask",
  "pdf-tools": "dunn/emacs",
  "pebble-sdk": "pebble/pebble-sdk",
  "quassel": "homebrew/cask",
  "sqlitebrowser": "homebrew/cask",
  "transmission-remote-gtk": "homebrew/cask/transmission-remote-gui",
  "tuntap": "homebrew/cask"
  "iotop": "linuxbrew/extra",
  "libpipeline": "linuxbrew/extra",
  "man-db": "linuxbrew/extra",
  "strace": "linuxbrew/extra",
}
'
Please report this bug:
  https://github.com/Linuxbrew/brew/wiki/troubleshooting
/usr/lib/ruby/2.5.0/json/common.rb:156:in `parse'
/usr/lib/ruby/2.5.0/json/common.rb:156:in `parse'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/tap.rb:513:in `tap_migrations'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/tap.rb:655:in `tap_migrations'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formulary.rb:209:in `formula_name_path'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formulary.rb:189:in `initialize'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formulary.rb:360:in `new'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formulary.rb:360:in `loader_for'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formulary.rb:280:in `factory'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formulary.rb:311:in `from_keg'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formulary.rb:294:in `from_rack'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula.rb:1389:in `block in installed'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula.rb:1387:in `each'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula.rb:1387:in `flat_map'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula.rb:1387:in `installed'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/cmd/upgrade.rb:35:in `upgrade'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/brew.rb:101:in `<main>'
```
- What you expected to happen
Update should succeed and subsequent commands should work.
- Step-by-step reproduction instructions (by running `brew` commands)
`brew upgrade` and kaboom...

**Comment by thedrow** [comment]
Possibly a duplicate of #715

**Comment by iMichka** [comment]
Fixed by https://github.com/Linuxbrew/homebrew-core/pull/7851
