### ISSUE TITLE
brew audit results in error, while installing rubocop

### ISSUE THREAD

**Issue by bukzor** [Linuxbrew/brew#731]
- [x] ran a `brew` command and reproduced the problem with multiple formulae?
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
```
$ brew doctor
Your system is ready to brew.
```
- [x] ran `brew config` and `brew doctor` and included their output with your issue?
```
$ brew config
HOMEBREW_VERSION: 1.6.3-3-gdca45ef
ORIGIN: git@github.com:Linuxbrew/brew.git
HEAD: dca45ef6aa87bbf53fb468115287e17f7e15d9e8
Last commit: 3 weeks ago
Core tap ORIGIN: https://github.com/Linuxbrew/homebrew-core
Core tap HEAD: 8b6fb16a02a71d7e91cc4b2cc4e6e7618306b25c
Core tap last commit: 17 minutes ago
HOMEBREW_PREFIX: /home/buck/prefix/brew
HOMEBREW_REPOSITORY: /home/buck/prefix/brew
HOMEBREW_CELLAR: /home/buck/prefix/brew/Cellar
HOMEBREW_CACHE: /home/buck/.cache/Homebrew
HOMEBREW_CASK_OPTS: --caskroom=~/Caskroom --binarydir=~/prefix/brew/bin
HOMEBREW_DEV_CMD_RUN: 1
HOMEBREW_MAKE_JOBS: 24
HOMEBREW_VERBOSE: 1
HOMEBREW_VISUAL: vim
CPU: octa-core 64-bit sandybridge
Homebrew Ruby: 2.3.3 => /usr/bin/ruby2.3
Clang: 4.0 build 401
Git: 2.14.1 => /usr/bin/git
Curl: 7.55.1 => /usr/bin/curl
Java: N/A
Kernel: Linux 4.13.0-43-lowlatency x86_64 GNU/Linux
OS: Ubuntu 17.10 (artful)
Host glibc: 2.26
/usr/bin/gcc: 7.2.0
glibc: N/A
gcc: N/A
xorg: N/A
```

To help us debug your issue please explain:
- What you were trying to do (and why)
`brew audit --strict jdk`, because of https://github.com/Linuxbrew/brew/issues/700 and https://github.com/Linuxbrew/homebrew-core/commit/8b6fb16a02a71d7e91cc4b2cc4e6e7618306b25c and https://github.com/Linuxbrew/homebrew-core/blob/master/CONTRIBUTING.md#contribute-a-fix-to-the-foo-formula

- What happened (include command output)
```
$ brew audit --strict jdk
==> Installing or updating 'rubocop' gem
Error: installing into parent path assets/logo.png of /home/buck/prefix/brew/Library/Homebrew/vendor/bundle/ruby/2.3.0/gems/rubocop-0.55.0 is not allowed
```

- What you expected to happen
Oh, you know...

- Step-by-step reproduction instructions (by running `brew` commands)
`brew audit --strict jdk`, I hope? Otherwise I really don't know.

**Comment by sjackman** [comment]
Are you able to reproduce this issue in a Docker image, particularly `linuxbrew/linuxbrew`? It'll make it easier to troubleshoot if you can.

**Comment by bukzor** [comment]
If I mount nothing to the image, `brew audit` works as expected. If I mount my local brew prefix, I get a different error:

```
$ docker run -v $HOME/prefix/brew:/home/linuxbrew/.linuxbrew -ti linuxbrew/linuxbrew brew audit --strict jdk
==> Downloading https://homebrew.bintray.com/bottles-portable-ruby/portable-ruby-2.3.3_2.x86_64_linux.bottle.tar.gz
######################################################################## 100.0%
==> Pouring portable-ruby-2.3.3_2.x86_64_linux.bottle.tar.gz
==> Installing or updating 'rubocop' gem
Successfully installed rubocop-0.55.0
1 gem installed
Error: cannot load such file -- parser
Please report this bug:
  https://github.com/Linuxbrew/brew/wiki/troubleshooting
/home/linuxbrew/.linuxbrew/Library/Homebrew/vendor/portable-ruby/2.3.3_2/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/home/linuxbrew/.linuxbrew/Library/Homebrew/vendor/portable-ruby/2.3.3_2/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/home/linuxbrew/.linuxbrew/Library/Homebrew/vendor/bundle/ruby/2.3.0/gems/rubocop-0.55.0/lib/rubocop.rb:3:in `<top (required)>'
/home/linuxbrew/.linuxbrew/Library/Homebrew/vendor/portable-ruby/2.3.3_2/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:127:in `require'
/home/linuxbrew/.linuxbrew/Library/Homebrew/vendor/portable-ruby/2.3.3_2/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:127:in `rescue in require'
/home/linuxbrew/.linuxbrew/Library/Homebrew/vendor/portable-ruby/2.3.3_2/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:40:in `require'
/home/linuxbrew/.linuxbrew/Library/Homebrew/style.rb:21:in `check_style_impl'
/home/linuxbrew/.linuxbrew/Library/Homebrew/style.rb:14:in `check_style_json'
/home/linuxbrew/.linuxbrew/Library/Homebrew/dev-cmd/audit.rb:119:in `audit'
/home/linuxbrew/.linuxbrew/Library/Homebrew/brew.rb:99:in `<main>'
```

The biggest difference seems to be the use of bottled ruby, but if I install ruby via apt, there's no real difference:

`$ docker run -v $HOME/prefix/brew:/home/linuxbrew/.linuxbrew -ti linuxbrew/linuxbrew sh -c 'sudo apt update &&sudo apt install ruby && brew audit --strict jdk'`

The strange thing is that it still insists on downloading a bottled ruby, although not so on my host system.

**Comment by bukzor** [comment]
Back on the host system, the use of bottled ruby changes my error message:

```
$ brew -v audit -vd --strict jdk
/home/buck/prefix/brew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /home/buck/prefix/brew/Library/Taps/homebrew/homebrew-core/Formula/binutils.rb
/home/buck/prefix/brew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /home/buck/prefix/brew/Library/Taps/homebrew/homebrew-core/Formula/make.rb
/home/buck/prefix/brew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /home/buck/prefix/brew/Library/Taps/homebrew/homebrew-core/Formula/jdk.rb
Error: No such file or directory - rubocop
/home/buck/prefix/brew/Library/Homebrew/vendor/portable-ruby/2.3.3_2/lib/ruby/2.3.0/open3.rb:199:in `spawn'
/home/buck/prefix/brew/Library/Homebrew/vendor/portable-ruby/2.3.3_2/lib/ruby/2.3.0/open3.rb:199:in `popen_run'
/home/buck/prefix/brew/Library/Homebrew/vendor/portable-ruby/2.3.3_2/lib/ruby/2.3.0/open3.rb:95:in `popen3'
/home/buck/prefix/brew/Library/Homebrew/vendor/portable-ruby/2.3.3_2/lib/ruby/2.3.0/open3.rb:258:in `capture3'
/home/buck/prefix/brew/Library/Homebrew/style.rb:91:in `check_style_impl'
/home/buck/prefix/brew/Library/Homebrew/style.rb:14:in `check_style_json'
/home/buck/prefix/brew/Library/Homebrew/dev-cmd/audit.rb:119:in `audit'
/home/buck/prefix/brew/Library/Homebrew/brew.rb:99:in `<main>'
```

If I blow away the gems (but leave bottled ruby intact) and try again, it works correctly.

```
$ rm -rf Library/Homebrew/vendor/bundle/ruby/2.3.0/

$ brew -v audit -vd --strict jdk                   
/home/buck/prefix/brew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /home/buck/prefix/brew/Library/Taps/homebrew/homebrew-core/Formula/binutils.rb
/home/buck/prefix/brew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /home/buck/prefix/brew/Library/Taps/homebrew/homebrew-core/Formula/make.rb
/home/buck/prefix/brew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /home/buck/prefix/brew/Library/Taps/homebrew/homebrew-core/Formula/jdk.rb
==> Installing or updating 'rubocop' gem
Fetching: parallel-1.12.1.gem (100%)
Successfully installed parallel-1.12.1
Fetching: ast-2.4.0.gem (100%)
Successfully installed ast-2.4.0
Fetching: parser-2.5.1.0.gem (100%)
Successfully installed parser-2.5.1.0
Fetching: powerpack-0.1.2.gem (100%)
Successfully installed powerpack-0.1.2
Fetching: rainbow-3.0.0.gem (100%)
Successfully installed rainbow-3.0.0
Fetching: ruby-progressbar-1.9.0.gem (100%)
Successfully installed ruby-progressbar-1.9.0
Fetching: unicode-display_width-1.4.0.gem (100%)
Successfully installed unicode-display_width-1.4.0
Fetching: rubocop-0.55.0.gem (100%)
Successfully installed rubocop-0.55.0
8 gems installed
/home/buck/prefix/brew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /home/buck/prefix/brew/Library/Taps/homebrew/homebrew-core/Formula/jdk@8.rb
/home/buck/prefix/brew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /home/buck/prefix/brew/Library/Taps/homebrew/homebrew-core/Formula/jdk@7.rb
/home/buck/prefix/brew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /home/buck/prefix/brew/Library/Taps/homebrew/homebrew-core/Formula/curl.rb
/home/buck/prefix/brew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /home/buck/prefix/brew/Library/Taps/homebrew/homebrew-core/Formula/openssl.rb
/home/buck/prefix/brew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /home/buck/prefix/brew/Library/Taps/homebrew/homebrew-core/Formula/pkg-config.rb
/home/buck/prefix/brew/Library/Homebrew/brew.rb (Formulary::FormulaContentsLoader): loading /home/buck/prefix/brew/Library/Taps/homebrew/homebrew-core/Formula/jdk.rb
/home/buck/prefix/brew/Library/Homebrew/brew.rb (Formulary::FormulaContentsLoader): loading /home/buck/prefix/brew/Library/Taps/homebrew/homebrew-core/Formula/jdk.rb
/home/buck/prefix/brew/Library/Homebrew/brew.rb (Formulary::FormulaContentsLoader): loading /home/buck/prefix/brew/Library/Taps/homebrew/homebrew-core/Formula/jdk.rb
/home/buck/prefix/brew/Library/Homebrew/brew.rb (Formulary::FormulaContentsLoader): loading /home/buck/prefix/brew/Library/Taps/homebrew/homebrew-core/Formula/jdk.rb
/home/buck/prefix/brew/Library/Homebrew/brew.rb (Formulary::FormulaContentsLoader): loading /home/buck/prefix/brew/Library/Taps/homebrew/homebrew-core/Formula/jdk.rb
/home/buck/prefix/brew/Library/Homebrew/brew.rb (Formulary::FormulaContentsLoader): loading /home/buck/prefix/brew/Library/Taps/homebrew/homebrew-core/Formula/jdk.rb
jdk:
  * C: 2: col 62: Description shouldn't end with a full stop
  * C: 8: col 6: Don't use OS.linux?; Homebrew/core only supports macOS
  * C: 11: col 9: Don't use OS.mac?; Homebrew/core only supports macOS
  * C: 21: col 54: Don't use OS.mac?; Homebrew/core only supports macOS
  * C: 26: col 1: Use 2 spaces for indentation in a heredoc.
Error: 5 problems in 1 formula
```

I don't really know anything about ruby or gems, so I can't provide any insight or creative debugging.

**Comment by bukzor** [comment]
Ah, I expect this has something to do with it:
```
$ echo $GEM_HOME 
/home/buck/prefix/rubygems
```

**Comment by bukzor** [comment]
I tried a whole bunch of variations of:
 * set $GEM_HOME
 * apt install ruby
 * rm -rf vendor/portable-ruby
 * rm -rf vendor/bundle

but it won't reproduce the problem in the docker image. It doesn't seem to ever use $GEM_HOME, nor /usr/bin/ruby.

**Comment by sjackman** [comment]
I'm afraid that I'm not terribly knowledgable of troubleshooting Ruby gems either. Sorry that I can't be of more help.

**Comment by bukzor** [comment]
Since I can't reproduce it, and I've found a workaround, let's close this and reopen if it re-emerges.
