### ISSUE TITLE
Bottle upload currently fails with release 1.7.0

### ISSUE THREAD

**Issue by iMichka** [Linuxbrew/brew#759]
The first issue encountered was fixed: https://github.com/Linuxbrew/homebrew-developer/pull/84

On the test-bot repo, the tests fail with:
```
Cloning into '/usr/local/Homebrew/Library/Taps/homebrew/homebrew-test-bot'...
remote: Counting objects: 2492, done.
remote: Compressing objects: 100% (21/21), done.
remote: Total 2492 (delta 8), reused 22 (delta 5), pack-reused 2463
Receiving objects: 100% (2492/2492), 573.77 KiB | 7.55 MiB/s, done.
Resolving deltas: 100% (820/820), done.
Tapped 1 command and 1 formula (29 files, 722.3KB).
Homebrew/homebrew-test-bot 275b884 (Merge pull request #167 from commitay/high-sierra)
ARGV: --verbose --ci-auto --no-pull --ci-master --cleanup --test-default-formula --fast
Error: no implicit conversion of nil into String
/usr/local/Homebrew/Library/Homebrew/utils/popen.rb:30:in `exec'
/usr/local/Homebrew/Library/Homebrew/utils/popen.rb:30:in `block in popen'
/usr/local/Homebrew/Library/Homebrew/utils/popen.rb:23:in `popen'
/usr/local/Homebrew/Library/Homebrew/utils/popen.rb:23:in `popen'
/usr/local/Homebrew/Library/Homebrew/utils/popen.rb:3:in `popen_read'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-test-bot/cmd/brew-test-bot.rb:451:in `download'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-test-bot/cmd/brew-test-bot.rb:1253:in `run'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-test-bot/cmd/brew-test-bot.rb:1604:in `test_bot'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-test-bot/cmd/brew-test-bot.rb:1699:in `<top (required)>'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/local/Homebrew/Library/Homebrew/utils.rb:18:in `require?'
/usr/local/Homebrew/Library/Homebrew/brew.rb:93:in `<main>'
```

I guess that this is preventing the bottle upload too and will need to be fixed.

**Comment by iMichka** [comment]
Here are the impacted lines:

> /home/travis/.linuxbrew/Homebrew/Library/Taps/linuxbrew/homebrew-test-bot/cmd/brew-test-bot.rb:409:in `merge_commit?'

> /home/travis/.linuxbrew/Homebrew/Library/Taps/linuxbrew/homebrew-test-bot/cmd/brew-test-bot.rb:464:in `download'

> /home/travis/.linuxbrew/Homebrew/Library/Taps/linuxbrew/homebrew-test-bot/cmd/brew-test-bot.rb:397:in `diff_formulae'

> /usr/local/Homebrew/Library/Taps/homebrew/homebrew-test-bot/cmd/brew-test-bot.rb:451:in `download'

Would this means the `@repository` is nil? Or is this a red herring.

**Comment by iMichka** [comment]
I was able to find back the right credentials to use for the AWS logs login ...
It seems to me that the errors above are a red herring. Probably a wrong test configuration.

Looking at the aws script, this seems to be wrong:
https://github.com/Linuxbrew/linuxbrew-lambda/blob/master/index.js#L35

Also, I am unsure about the logic here:
https://github.com/Linuxbrew/linuxbrew-lambda/blob/master/index.js#L64-L66
No auto update, and then update is called manually.

It looks like the command on aws never returns:
```
2018-07-24T22:27:13.123Z	54def381-8f90-11e8-9a9b-a549ab845c02	/tmp/brew/bin/brew [ 'pull-circle',
'--ci-upload',
'--keep-old',
'https://github.com/Linuxbrew/homebrew-core/pull/8436' ] ==> homebrew/core#8436
https://circleci.com/api/v1.1/project/github/Linuxbrew/homebrew-core/latest/artifacts?branch=pull/8436
```

**Comment by iMichka** [comment]
Fixed by  https://github.com/Linuxbrew/homebrew-developer/pull/85
