### ISSUE TITLE
The Last Merge Bug

### ISSUE THREAD

**Issue by makamekm** [Linuxbrew/brew#771]
Hello! I try to install gcc with the last commit: `HOMEBREW_NO_AUTO_UPDATE=1 HOMEBREW_BUILD_FROM_SOURCE=1 brew install gcc --without-glibc`

```
==> Installing gcc --without-glibc
==> Downloading https://ftp.gnu.org/gnu/gcc/gcc-5.5.0/gcc-5.5.0.tar.xz
######################################################################## 100.0%
==> Patching
can't find file to patch at input line 5
Perhaps you used the wrong -p or --strip option?
The text leading up to this was:
--------------------------
|diff --git a/gcc/graphite.h b/gcc/graphite.h
|index 4e0e58c..be0a22b 100644
|--- a/gcc/graphite.h
|+++ b/gcc/graphite.h
--------------------------
No file to patch.  Skipping patch.
1 out of 1 hunk ignored
Error: undefined method `ErrorDuringExecution' for Utils:Module
/home/vx00727/.apps/Library/Homebrew/utils/popen.rb:18:in `safe_popen_write'
/home/vx00727/.apps/Library/Homebrew/patch.rb:70:in `apply'
/home/vx00727/.apps/Library/Homebrew/formula.rb:1104:in `each'
/home/vx00727/.apps/Library/Homebrew/formula.rb:1104:in `patch'
/home/vx00727/.apps/Library/Homebrew/build.rb:130:in `block (2 levels) in install'
/home/vx00727/.apps/Library/Homebrew/formula.rb:1117:in `block in brew'
/home/vx00727/.apps/Library/Homebrew/formula.rb:2037:in `block (2 levels) in stage'
/home/vx00727/.apps/Library/Homebrew/utils.rb:564:in `with_env'
/home/vx00727/.apps/Library/Homebrew/formula.rb:2036:in `block in stage'
/home/vx00727/.apps/Library/Homebrew/resource.rb:120:in `block in unpack'
/home/vx00727/.apps/Library/Homebrew/resource.rb:189:in `block in mktemp'
/home/vx00727/.apps/Library/Homebrew/mktemp.rb:55:in `block in run'
/home/vx00727/.apps/Library/Homebrew/mktemp.rb:55:in `chdir'
/home/vx00727/.apps/Library/Homebrew/mktemp.rb:55:in `run'
/home/vx00727/.apps/Library/Homebrew/resource.rb:188:in `mktemp'
/home/vx00727/.apps/Library/Homebrew/resource.rb:115:in `unpack'
/home/vx00727/.apps/Library/Homebrew/resource.rb:93:in `stage'
/home/vx00727/.apps/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/forwardable.rb:202:in `stage'
/home/vx00727/.apps/Library/Homebrew/formula.rb:2014:in `stage'
/home/vx00727/.apps/Library/Homebrew/formula.rb:1112:in `brew'
/home/vx00727/.apps/Library/Homebrew/build.rb:124:in `block in install'
/home/vx00727/.apps/Library/Homebrew/utils.rb:564:in `with_env'
/home/vx00727/.apps/Library/Homebrew/build.rb:121:in `install'
/home/vx00727/.apps/Library/Homebrew/build.rb:202:in `<main>'
```

- [+] ran a `brew` command and reproduced the problem with multiple formulae? If it's a problem with a single, official formula (not cask) please file this issue at Linuxbrew/homebrew-core: https://github.com/Linuxbrew/homebrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [-] ran `brew update` and can still reproduce the problem?
- [-] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [-] ran `brew config` and `brew doctor` and included their output with your issue?

**Comment by iMichka** [comment]
Hi. I think the patch applied in the gcc.rb formula needs to be “removed” by using: unless OS.mac?. Mind opening a pull request in the core repository? I’m home in around 1 hour and will fix it then.

**Comment by iMichka** [comment]
Will be fixed by https://github.com/Linuxbrew/homebrew-core/pull/8720
