### ISSUE TITLE
brew tests fail on Ubuntu 14.04

### ISSUE THREAD

**Issue by bw-yuhogg** [Linuxbrew/brew#78]
`brew tests` fail on Ubuntu 14.04. Might be because of my recent installation of LLVM, but not sure.

```
  1) Failure:
IntegrationCommandTests#test_reinstall [/home/bob/.linuxbrew/Library/Homebrew/test/test_integration_cmds.rb:79]:
--- expected
+++ actual
@@ -1 +1 @@
-0
+1



  2) Failure:
IntegrationCommandTests#test_upgrade [/home/bob/.linuxbrew/Library/Homebrew/test/test_integration_cmds.rb:79]:
--- expected
+++ actual
@@ -1 +1 @@
-0
+1



  3) Failure:
IntegrationCommandTests#test_bottle [/home/bob/.linuxbrew/Library/Homebrew/test/test_integration_cmds.rb:79]:
--- expected
+++ actual
@@ -1 +1 @@
-0
+1



  4) Failure:
IntegrationCommandTests#test_install [/home/bob/.linuxbrew/Library/Homebrew/test/test_integration_cmds.rb:79]:
--- expected
+++ actual
@@ -1 +1 @@
-0
+1



  5) Failure:
IntegrationCommandTests#test_pin_unpin [/home/bob/.linuxbrew/Library/Homebrew/test/test_integration_cmds.rb:79]:
--- expected
+++ actual
@@ -1 +1 @@
-0
+1



  6) Failure:
IntegrationCommandTests#test_uninstall [/home/bob/.linuxbrew/Library/Homebrew/test/test_integration_cmds.rb:79]:
--- expected
+++ actual
@@ -1 +1 @@
-0
+1



  7) Error:
InstallTests#test_a_basic_install:
CompilerSelectionError: testball cannot be built with any available compilers.
To install this formula, you may need to either:
  brew install apple-gcc42
or:
  brew install gcc

    /home/bob/.linuxbrew/Library/Homebrew/compilers.rb:106:in `compiler'
    /home/bob/.linuxbrew/Library/Homebrew/compilers.rb:88:in `select_for'
    /home/bob/.linuxbrew/Library/Homebrew/extend/ENV/shared.rb:169:in `compiler'
    /home/bob/.linuxbrew/Library/Homebrew/extend/ENV/std.rb:77:in `setup_build_environment'
    /home/bob/.linuxbrew/Library/Homebrew/build.rb:91:in `install'
    /home/bob/.linuxbrew/Library/Homebrew/build.rb:178:in `<main>'


  8) Error:
InstallTests#test_bottle_unneeded_formula_install:
CompilerSelectionError: testball cannot be built with any available compilers.
To install this formula, you may need to either:
  brew install apple-gcc42
or:
  brew install gcc

    /home/bob/.linuxbrew/Library/Homebrew/compilers.rb:106:in `compiler'
    /home/bob/.linuxbrew/Library/Homebrew/compilers.rb:88:in `select_for'
    /home/bob/.linuxbrew/Library/Homebrew/extend/ENV/shared.rb:169:in `compiler'
    /home/bob/.linuxbrew/Library/Homebrew/extend/ENV/std.rb:77:in `setup_build_environment'
    /home/bob/.linuxbrew/Library/Homebrew/build.rb:91:in `install'
    /home/bob/.linuxbrew/Library/Homebrew/build.rb:178:in `<main>'
```

**Comment by bw-yuhogg** [comment]
Nope, uninstalling `llvm` doesn't fix it. Darn.

**Comment by sjackman** [comment]
Circle is running Ubuntu 14, and `brew tests` works there. Not saying this bug isn't real, but it doesn't affect all Ubuntu 14 systems.

**Comment by bw-yuhogg** [comment]
I don't think keeping this issue open has much value at this point.
