### ISSUE TITLE
Error: undefined method `sdk_path_if_needed' for OS::Mac:Module

### ISSUE THREAD

**Issue by kennethdave** [Linuxbrew/brew#827]
```
During installation got an issue below, please advise. Thanks.
==> Installing dependencies for node: python@2, icu4c
==> Installing node dependency: python@2
==> Downloading https://www.python.org/ftp/python/2.7.15/Python-2.7.15.tar.xz
Already downloaded: /home/ec2-user/.cache/Homebrew/python@2-2.7.15.tar.xz
==> Verifying python@2-2.7.15.tar.xz checksum
tar xf /home/ec2-user/.cache/Homebrew/python@2-2.7.15.tar.xz -C /tmp/d20180826-3521-rvhobn
Error: undefined method `sdk_path_if_needed' for OS::Mac:Module
Please report this bug:
  https://github.com/Linuxbrew/brew/wiki/troubleshooting
/home/ec2-user/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/python@2.rb:117:in `install'
/home/ec2-user/.linuxbrew/Homebrew/Library/Homebrew/build.rb:153:in `block (2 levels) in install'
/home/ec2-user/.linuxbrew/Homebrew/Library/Homebrew/formula.rb:1117:in `block in brew'
/home/ec2-user/.linuxbrew/Homebrew/Library/Homebrew/formula.rb:2037:in `block (2 levels) in stage'
/home/ec2-user/.linuxbrew/Homebrew/Library/Homebrew/utils.rb:564:in `with_env'
/home/ec2-user/.linuxbrew/Homebrew/Library/Homebrew/formula.rb:2036:in `block in stage'
/home/ec2-user/.linuxbrew/Homebrew/Library/Homebrew/resource.rb:120:in `block in unpack'
/home/ec2-user/.linuxbrew/Homebrew/Library/Homebrew/resource.rb:189:in `block in mktemp'
/home/ec2-user/.linuxbrew/Homebrew/Library/Homebrew/mktemp.rb:55:in `block in run'
/home/ec2-user/.linuxbrew/Homebrew/Library/Homebrew/mktemp.rb:55:in `chdir'
/home/ec2-user/.linuxbrew/Homebrew/Library/Homebrew/mktemp.rb:55:in `run'
/home/ec2-user/.linuxbrew/Homebrew/Library/Homebrew/resource.rb:188:in `mktemp'
/home/ec2-user/.linuxbrew/Homebrew/Library/Homebrew/resource.rb:115:in `unpack'
/home/ec2-user/.linuxbrew/Homebrew/Library/Homebrew/resource.rb:93:in `stage'
/home/ec2-user/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/forwardable.rb:202:in `stage'
/home/ec2-user/.linuxbrew/Homebrew/Library/Homebrew/formula.rb:2014:in `stage'
/home/ec2-user/.linuxbrew/Homebrew/Library/Homebrew/formula.rb:1112:in `brew'
/home/ec2-user/.linuxbrew/Homebrew/Library/Homebrew/build.rb:124:in `block in install'
/home/ec2-user/.linuxbrew/Homebrew/Library/Homebrew/utils.rb:564:in `with_env'
/home/ec2-user/.linuxbrew/Homebrew/Library/Homebrew/build.rb:121:in `install'
/home/ec2-user/.linuxbrew/Homebrew/Library/Homebrew/build.rb:202:in `<main>'
```

**Comment by sjackman** [comment]
Please surround copied-and-pasted logs with triple back ticks. See [GitHub Help / Quoting Code](https://help.github.com/articles/basic-writing-and-formatting-syntax/#quoting-code).

**Comment by sjackman** [comment]
Thanks for the bug report, @kennethdave. Fixed by PR https://github.com/Linuxbrew/homebrew-core/pull/9073

**Comment by kennethdave** [comment]
Thanks for the fixed, @sjackman. :)

**Comment by sjackman** [comment]
Happy to help!
