### ISSUE TITLE
installation fails

### ISSUE THREAD

**Issue by dimmonn** [Linuxbrew/brew#840]
```
Error: /root/.linuxbrew/Library/Taps/homebrew/homebrew-core/Formula/git.rb:174: syntax error, unexpected $undefined, expecting keyword_end
      \thelper = osxkeychain
       ^
Please report this bug:
    https://github.com/Linuxbrew/linuxbrew/blob/master/share/doc/homebrew/Troubleshooting.md#troubleshooting
/root/.linuxbrew/Library/Homebrew/formulary.rb:21:in `module_eval'
/root/.linuxbrew/Library/Homebrew/formulary.rb:21:in `load_formula'
/root/.linuxbrew/Library/Homebrew/formulary.rb:34:in `load_formula_from_path'
/root/.linuxbrew/Library/Homebrew/formulary.rb:83:in `load_file'
/root/.linuxbrew/Library/Homebrew/formulary.rb:74:in `klass'
/root/.linuxbrew/Library/Homebrew/formulary.rb:70:in `get_formula'
/root/.linuxbrew/Library/Homebrew/formulary.rb:207:in `factory'
/root/.linuxbrew/Library/Homebrew/formulary.rb:352:in `find_with_priority'
/root/.linuxbrew/Library/Homebrew/extend/ARGV.rb:20:in `block in formulae'
/root/.linuxbrew/Library/Homebrew/extend/ARGV.rb:16:in `map'
/root/.linuxbrew/Library/Homebrew/extend/ARGV.rb:16:in `formulae'
/root/.linuxbrew/Library/Homebrew/cmd/install.rb:44:in `install'
/root/.linuxbrew/Library/brew.rb:84:in `<main>'
==> Tapping homebrew/dupes
Cloning into '/root/.linuxbrew/Library/Taps/homebrew/homebrew-dupes'...
remote: Counting objects: 5, done.
remote: Compressing objects: 100% (5/5), done.
remote: Total 5 (delta 0), reused 3 (delta 0), pack-reused 0
Unpacking objects: 100% (5/5), done.
Tapped 0 formulae (29 files, 20.9K)
Error: /root/.linuxbrew/Library/Taps/homebrew/homebrew-core/Formula/coreutils.rb:86: syntax error, unexpected <<
  def caveats; <<~EOS
                 ^
/root/.linuxbrew/Library/Taps/homebrew/homebrew-core/Formula/coreutils.rb:90: syntax error, unexpected tIDENTIFIER, expecting keyword_end
    can add a "gnubin" directory to your PATH from your bashrc like:
                                ^
/root/.linuxbrew/Library/Taps/homebrew/homebrew-core/Formula/coreutils.rb:90: syntax error, unexpected ':', expecting keyword_end
/root/.linuxbrew/Library/Taps/homebrew/homebrew-core/Formula/coreutils.rb:92: dynamic constant assignment
        PATH="#{opt_libexec}/gnubin:$PATH"
             ^
/root/.linuxbrew/Library/Taps/homebrew/homebrew-core/Formula/coreutils.rb:94: dynamic constant assignment
    Additionally, you can access their man pag...
                 ^
/root/.linuxbrew/Library/Taps/homebrew/homebrew-core/Formula/coreutils.rb:94: syntax error, unexpected tIDENTIFIER, expecting keyword_do or '{' or '('
    Additionally, you can access their man pages with ...
                         ^
/root/.linuxbrew/Library/Taps/homebrew/homebrew-core/Formula/coreutils.rb:95: syntax error, unexpected tIDENTIFIER, expecting keyword_end
    the "gnuman" directory to your MANPATH from your bashrc as well:
                          ^
/root/.linuxbrew/Library/Taps/homebrew/homebrew-core/Formula/coreutils.rb:95: syntax error, unexpected ':', expecting keyword_end
/root/.linuxbrew/Library/Taps/homebrew/homebrew-core/Formula/coreutils.rb:97: dynamic constant assignment
        MANPATH="#{opt_libexec}/gnuman:$MANPATH"
                ^
Please report this bug:
    https://github.com/Linuxbrew/linuxbrew/blob/master/share/doc/homebrew/Troubleshooting.md#troubleshooting
/root/.linuxbrew/Library/Homebrew/formulary.rb:21:in `module_eval'
/root/.linuxbrew/Library/Homebrew/formulary.rb:21:in `load_formula'
/root/.linuxbrew/Library/Homebrew/formulary.rb:34:in `load_formula_from_path'
/root/.linuxbrew/Library/Homebrew/formulary.rb:83:in `load_file'
/root/.linuxbrew/Library/Homebrew/formulary.rb:74:in `klass'
/root/.linuxbrew/Library/Homebrew/formulary.rb:70:in `get_formula'
/root/.linuxbrew/Library/Homebrew/formulary.rb:207:in `factory'
/root/.linuxbrew/Library/Homebrew/formulary.rb:352:in `find_with_priority'
/root/.linuxbrew/Library/Homebrew/extend/ARGV.rb:20:in `block in formulae'
/root/.linuxbrew/Library/Homebrew/extend/ARGV.rb:16:in `map'
/root/.linuxbrew/Library/Homebrew/extend/ARGV.rb:16:in `formulae'
/root/.linuxbrew/Library/Homebrew/cmd/install.rb:44:in `install'
/root/.linuxbrew/Library/brew.rb:84:in `<main>'
./install_linuxbrew_on_centos7.sh: line 53: ln: command not found
./install_linuxbrew_on_centos7.sh: line 54: ln: command not found
./install_linuxbrew_on_centos7.sh: line 55: ln: command not found
```

**Comment by sjackman** [comment]
Please surround copied-and-pasted logs with triple back ticks. See [GitHub Help / Quoting Code](https://help.github.com/articles/basic-writing-and-formatting-syntax/#quoting-code).

**Comment by sjackman** [comment]
As a normal user, preferably with `sudo` access, run…
```sh
sh -c "$(curl -fsSL https://raw.githubusercontent.com/Linuxbrew/install/master/install.sh)"
```
See http://linuxbrew.sh/#install-linuxbrew

**Comment by dimmonn** [comment]
it doesn't work, I run centos7
```
[dima@dima ncs-run]$ echo 'export PATH="/home/dima/.linuxbrew/bin:$PATH"' >>~/.profile
[dima@dima ncs-run]$     echo 'export MANPATH="/home/dima/.linuxbrew/share/man:$MANPATH"' >>~/.profile
[dima@dima ncs-run]$     echo 'export INFOPATH="/home/dima/.linuxbrew/share/info:$INFOPATH"' >>~/.profile
[dima@dima ncs-run]$ brew install gcc
Error: The current working directory doesn't exist, cannot proceed.
[dima@dima ncs-run]$
```

**Comment by sjackman** [comment]
Please surround copied-and-pasted logs with triple back ticks. See [GitHub Help / Quoting Code](https://help.github.com/articles/basic-writing-and-formatting-syntax/#quoting-code).

**Comment by sjackman** [comment]
> Error: The current working directory doesn't exist, cannot proceed.

Your current working directory does not exist. See
```sh
pwd
ls $(pwd)
```
`cd` to a working directory that does exist.
