### ISSUE TITLE
Sticky bit - tmp is sticky

### ISSUE THREAD

**Issue by black-snow** [Linuxbrew/brew#852]
I did my daily `brew update && brew upgrade` and got this:

```
Error: An exception occured within a child process:
  ArgumentError: parent directory is world writable but not sticky
```

which is probably the same as these:
https://github.com/Homebrew/legacy-homebrew/issues/39475
https://github.com/Homebrew/brew/issues/477
https://github.com/Homebrew/legacy-homebrew/issues/45675
https://github.com/Linuxbrew/brew/issues/234

But my `/tmp/` already has the sticky bit set. I didn't change any of brew's configs. As expected doing a `chmod +t /tmp` didn't help.

How do I find out which directory is actually problematic?

I run linuxbrew on Ubuntu inside the WSL.

**Comment by sjackman** [comment]
Please report the output of…
```sh
echo $TMPDIR
stat $TMPDIR
stat /tmp
```

**Comment by eugenesvk** [comment]
I also started to have the same issue with upgrading  (also on Ubuntu 18 inside the WSL)
`$TMPDIR` was unset, so no stats there, but after I've set it to `/tmp` I get the same issue
`stat /tmp` is
```
  File: /tmp                                                             
  Size: 512             Blocks: 0          IO Block: 512    directory    
Device: 2h/2d   Inode: 281474977760305  Links: 1                         
Access: (1777/drwxrwxrwt)  Uid: (    0/    root)   Gid: (    0/    root) 
Access: 2016-03-23 23:54:45.000000000 +0300                              
Modify: 2018-10-02 00:34:10.432344900 +0300                              
Change: 2018-10-02 00:34:10.432344900 +0300                              
 Birth: -                                                                
```
Also tried to set/unset the sticky bit with  `chmod +t /tmp`, but it didn't help either

**Comment by sjackman** [comment]
Try `brew upgrade -dv`, which should give you a Ruby backtrace, and paste the results of the backtrace here.

**Comment by eugenesvk** [comment]
```
~ > brew upgrade -dv
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/argon2.rb
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/autoconf.rb
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/autojump.rb
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/bzip2.rb
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/curl.rb
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/expat.rb
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/fzf.rb
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/gcc.rb
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/glibc.rb
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/gdbm.rb
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/gettext.rb
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/git.rb
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/gmp.rb
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/isl.rb
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/isl@0.18.rb
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/libbsd.rb
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/libffi.rb
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/libmpc.rb
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/libtool.rb
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/libyaml.rb
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/m4.rb
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/mpfr.rb
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/ncurses.rb
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/node-build.rb
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/nodenv.rb
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/openssl.rb
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/patchelf.rb
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/pcre2.rb
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/pkg-config.rb
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/plenv.rb
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/pyenv.rb
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/rbenv.rb
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/rbenv-gemset.rb
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/readline.rb
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/ruby.rb
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/ruby-build.rb
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/sqlite.rb
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/xz.rb
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/zlib.rb
Error: Not upgrading 1 pinned package:
node-build 3.0.18
==> Upgrading 2 outdated packages, with result:
plenv 2.2.0 -> 2.3.0, ruby-build 20180329 -> 20180822
==> Upgrading plenv
rm /home/linuxbrew/.linuxbrew/bin/plenv
nice: cannot set niceness: Permission denied
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/build.rb (Formulary::FromPathLoader): loading /home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/plenv.rb
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/build.rb (Formulary::FormulaLoader): loading /home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/gcc.rb
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/build.rb (Formulary::FormulaLoader): loading /home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/glibc.rb
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/build.rb (Formulary::FormulaLoader): loading /home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/binutils.rb
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/build.rb (Formulary::FormulaLoader): loading /home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/make.rb
==> Downloading https://github.com/tokuhirom/plenv/archive/2.3.0.tar.gz
Already downloaded: /home/es/.cache/Homebrew/downloads/c0deece4f21cf9db2328587224ff6583ed10d3ef2e276dfcfd738f23350efb4d--plenv-2.3.0.tar.gz ==> Verifying c0deece4f21cf9db2328587224ff6583ed10d3ef2e276dfcfd738f23350efb4d--plenv-2.3.0.tar.gz checksum
tar xf /home/es/.cache/Homebrew/downloads/c0deece4f21cf9db2328587224ff6583ed10d3ef2e276dfcfd738f23350efb4d--plenv-2.3.0.tar.gz -C /tmp/d20181002-25897-1ld220s
cp -pR /tmp/d20181002-25897-1ld220s/plenv-2.3.0/. /tmp/plenv-20181002-25897-y3t5po/plenv-2.3.0
==> /home/linuxbrew/.linuxbrew/Cellar/plenv/2.3.0/bin/plenv rehash
==> Kept temporary files
Temporary files retained at /tmp/plenv-20181002-25897-y3t5po
ln -s ../Cellar/plenv/2.2.0/bin/plenv plenv
Error: An exception occured within a child process:
  ArgumentError: parent directory is world writable but not sticky
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/debrew.rb:11:in `raise'
/usr/lib/ruby/2.5.0/tmpdir.rb:93:in `mktmpdir'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/extend/pathname.rb:165:in `atomic_write'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/tab.rb:360:in `write'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/build.rb:158:in `block (2 levels) in install'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula.rb:1134:in `block in brew'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula.rb:2074:in `block (2 levels) in stage'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/utils.rb:523:in `with_env'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula.rb:2073:in `block in stage'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/resource.rb:103:in `block in unpack'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/resource.rb:173:in `block in mktemp'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/mktemp.rb:55:in `block in run'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/mktemp.rb:55:in `chdir'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/mktemp.rb:55:in `run'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/resource.rb:172:in `mktemp'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/resource.rb:98:in `unpack'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/resource.rb:75:in `stage'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula.rb:2049:in `stage'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula.rb:1129:in `brew'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/build.rb:125:in `block in install'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/utils.rb:523:in `with_env'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/build.rb:122:in `install'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/build.rb:203:in `<main>'
~ >
```

**Comment by eugenesvk** [comment]
Just FYI here is the `brew doctor` output
```
~ > brew doctor                                                                                                                       1⏎ 12sPlease note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: "config" scripts exist outside your system or Homebrew directories.
`./configure` scripts often look for *-config scripts to determine if
software packages are installed, and what additional flags to use when
compiling and linking.

Having additional scripts in your path can confuse software installed via
Homebrew if the config script overrides a system or Homebrew provided
script of the same name. We found the following "config" scripts:
  /home/es/.dev/.pyenv/shims/python-config
  /home/es/.dev/.pyenv/shims/python3-config
  /home/es/.dev/.pyenv/shims/python3.7-config
  /home/es/.dev/.pyenv/shims/python3.7m-config
  /usr/local/bin/gpg-error-config
  /usr/local/bin/ksba-config
  /usr/local/bin/libassuan-config
  /usr/local/bin/libgcrypt-config
  /usr/local/bin/npth-config
  /mnt/c/Dev/Python/Miniconda3/Library/bin/icu-config

Warning: Unbrewed header files were found in /usr/local/include.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected header files:
  /usr/local/include/assuan.h
  /usr/local/include/fuse3/cuse_lowlevel.h
  /usr/local/include/fuse3/fuse.h
  /usr/local/include/fuse3/fuse_common.h
  /usr/local/include/fuse3/fuse_lowlevel.h
  /usr/local/include/fuse3/fuse_opt.h
  /usr/local/include/gcrypt.h
  /usr/local/include/gpg-error.h
  /usr/local/include/ksba.h
  /usr/local/include/npth.h

Warning: Unbrewed .la files were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected .la files:
  /usr/local/lib/libassuan.la
  /usr/local/lib/libgcrypt.la
  /usr/local/lib/libgpg-error.la
  /usr/local/lib/libksba.la
  /usr/local/lib/libnpth.la
~
```

**Comment by sjackman** [comment]
Here's the line of code that's causing the exception:
https://github.com/Linuxbrew/brew/blob/eff380ed4278274191000f0d15d1f87b5d57d036/Library/Homebrew/extend/pathname.rb#L164-L165
called from here:
https://github.com/Linuxbrew/brew/blob/eff380ed4278274191000f0d15d1f87b5d57d036/Library/Homebrew/tab.rb#L360

I'm afraid I don't have a windows system on which to reproduce and troubleshoot this issue. I don't myself have much more capacity to help troubleshoot this issue. If someone is able to find a fix or workaround, please post here!

It would also be helpful to learn which versions of Linuxbrew/brew this issue affects.

**Comment by eugenesvk** [comment]
Not even a VM or something?
There also seems to be a very recent [v1.7.6 commit](https://github.com/Linuxbrew/brew/commit/ead23d1f4c6eb3ba83e3d126d3874609957325bd#diff-06540c12bb8e84922c0d329ed05b19bf
) that substantially changes the first line of code you're referencing. Do you see anything there that might give you a hint as to what the issue might be? Also, is there a simple (i.e. without having to reinstall everything) way to downgrade a version of Linuxbrew to see if a previous version is working? Thank you!

Here is the version output.
```
~ > brew config
HOMEBREW_VERSION: 1.7.6
ORIGIN: https://github.com/Linuxbrew/brew
HEAD: eff380ed4278274191000f0d15d1f87b5d57d036
Last commit: 8 days ago
Core tap ORIGIN: https://github.com/Linuxbrew/homebrew-core
Core tap HEAD: 5ac8a2ccf7be4928630b4147d9cfec6bccf7311f
Core tap last commit: 18 hours ago
HOMEBREW_PREFIX: /home/linuxbrew/.linuxbrew
HOMEBREW_CACHE: /home/es/.cache/Homebrew
HOMEBREW_DEV_CMD_RUN: 1
HOMEBREW_GIT: git
HOMEBREW_GITHUB_API_TOKEN: set
HOMEBREW_NO_ANALYTICS: 1
CPU: octa-core 64-bit ivybridge
Homebrew Ruby: 2.5.1 => /usr/bin/ruby2.5
Clang: N/A
Git: 2.19.0 => /home/linuxbrew/.linuxbrew/bin/git
Curl: 7.58.0 => /usr/bin/curl
Java: N/A
Kernel: Linux 4.4.0-17134-Microsoft x86_64 GNU/Linux
OS: Ubuntu 18.04.1 LTS (bionic)
Host glibc: 2.27
/usr/bin/gcc: 7.3.0
glibc: N/A
gcc: 5.5.0_4
xorg: N/A
~
```

**Comment by iMichka** [comment]
Does this new change help: https://github.com/Homebrew/brew/pull/5009 ?

**Comment by sjackman** [comment]
> Not even a VM or something?

I don't have a license for Windows. There's the possibility of using Azure Pipelines to test Linuxbrew on WSL.

**Comment by sjackman** [comment]
Thanks, Michka. PR https://github.com/Homebrew/brew/pull/5009 looks like the solution. This issue will be resolved in Linuxbrew 1.7.7.

**Comment by eugenesvk** [comment]
Thanks, can confirm this fix is working

**Comment by sjackman** [comment]
Excellent! I'm glad to hear it.

**Comment by black-snow** [comment]
Seems to be fixed, thanks!

**Comment by fuddlesworth** [comment]
Any update on when 1.7.7 is coming? This is a critical bug and basically makes linuxbrew unusable.

@sjackman

**Comment by sjackman** [comment]
We usually sync our releases of Linuxbrew/brew with Homebrew/brew, and Homebrew/brew 1.7.7 was released three hours ago (see https://github.com/Homebrew/brew/releases/tag/1.7.7). I've opened a PR to merge Homebrew/1.7.7 into Linuxbrew. https://github.com/Linuxbrew/brew/pull/863

**Comment by sjackman** [comment]
Linuxbrew/brew 1.7.7 has been released, which resolves this issue. https://github.com/Linuxbrew/brew/issues/1#issuecomment-429435549

**Comment by black-snow** [comment]
@iMichka I again experience this issue.

```
==> Upgrading valgrind
==> Downloading https://linuxbrew.bintray.com/bottles/valgrind-3.14.0.x86_64_linux.bottle.tar.gz

curl: (22) The requested URL returned error: 404 Not Found
Error: Failed to download resource "valgrind"
Download failed: https://linuxbrew.bintray.com/bottles/valgrind-3.14.0.x86_64_linux.bottle.tar.gz
Warning: Bottle installation failed: building from source.
nice: cannot set niceness: Permission denied
==> Downloading https://sourceware.org/pub/valgrind/valgrind-3.14.0.tar.bz2
Already downloaded: /home/rbergmann/.cache/Homebrew/downloads/d0869ed999423ebddfd052ddd970564467c98f4af055031d8a2a35356be29fc7--valgrind-3.14.0.tar.bz2
==> ./configure --prefix=/home/linuxbrew/.linuxbrew/Cellar/valgrind/3.14.0 --enable-only64bit
==> make
==> make install
Error: An exception occurred within a child process:
  ArgumentError: parent directory is world writable but not sticky
```

Let me know if I can help with more information. Latest Ubuntu inside WSL.

**Comment by sjackman** [comment]
@black-snow Please report the output of `brew config`.
I've opened PR https://github.com/Linuxbrew/homebrew-core/pull/10023 to build a bottle for `valgrind`.

**Comment by alyosha** [comment]
seems like this might be broken again in 1.8.0

**Comment by eugenesvk** [comment]
I've also started to have the same issue since **1.8.0** with several packages (e.g. **node-build** and **ruby-build**) and found out that the issue seems to be caused by this [commit ](https://github.com/Homebrew/brew/commit/98016b0ac61c3e078a4df34f1ec5d2792958dcd4#diff-06540c12bb8e84922c0d329ed05b19bf) changing **Library/Homebrew/extend/pathname.rb** file. When I revert this change, I can install upgrades without an issue. Though I don't understand what it does and whether by reverting it I've broken something else, so not sure what to do.
Would you please look into it to see what the best fix would be? Thank you

```
~ > brew config                                                                                                         1⏎ 47sHOMEBREW_VERSION: 1.8.0-dirty
ORIGIN: https://github.com/Linuxbrew/brew
HEAD: 8f5de98bcc40afe402969dff6794739979b00a09
Last commit: 5 days ago
Core tap ORIGIN: https://github.com/Linuxbrew/homebrew-core
Core tap HEAD: 2e2ed97c89f85d757e3680c4304fc2c420d283da
Core tap last commit: 5 hours ago
HOMEBREW_PREFIX: /home/linuxbrew/.linuxbrew
HOMEBREW_CACHE: /home/es/.cache/Homebrew
HOMEBREW_DEV_CMD_RUN: 1
HOMEBREW_GITHUB_API_TOKEN: set
HOMEBREW_NO_ANALYTICS: 1
CPU: octa-core 64-bit ivybridge
Homebrew Ruby: 2.5.1 => /usr/bin/ruby2.5
Clang: N/A
Git: 2.19.1 => /home/linuxbrew/.linuxbrew/bin/git
Curl: 7.58.0 => /usr/bin/curl
Kernel: Linux 4.4.0-17134-Microsoft x86_64 GNU/Linux
OS: Ubuntu 18.04.1 LTS (bionic)
Host glibc: 2.27
/usr/bin/gcc: 7.3.0
glibc: N/A
gcc: 5.5.0_4
xorg: N/A
```

**Comment by sjackman** [comment]
Here's the upstream Homebrew/brew PR that changed this behaviour: https://github.com/Homebrew/brew/pull/5127

**Comment by sjackman** [comment]
@eugenesvk Thanks for finding the particular commit that caused the trouble. I'll see if I can replicate the issue. In the mean time, reverting that commit seems like a reasonable workaround.

**Comment by sjackman** [comment]
Here's a related issue: https://github.com/bundler/bundler/issues/4599
Try the following command and see whether hopefully it resolves your issue.
```sh
find ~/.linuxbrew ~/.cache -type d -exec chmod 0755 {} +
```
I don't have access to a Windows machine, so I'm unable to test troubleshoot this issue myself.

**Comment by sjackman** [comment]
This patch may work around the issue until a proper fix is found.
```diff
diff --git a/Library/Homebrew/extend/pathname.rb b/Library/Homebrew/extend/pathname.rb
index 513e11290..6ba55cdf2 100644
--- a/Library/Homebrew/extend/pathname.rb
+++ b/Library/Homebrew/extend/pathname.rb
@@ -166,6 +166,7 @@ class Pathname
     # for https://github.com/rails/rails/pull/34037.
     Dir.mktmpdir(".d", dirname) do |tmpdir|
       should_fix_sticky_bit = dirname.world_writable? && !dirname.sticky?
+      should_fix_sticky_bit = true
       FileUtils.chmod "+t", dirname if should_fix_sticky_bit
       begin
         File.atomic_write(self, tmpdir) do |file|
```

**Comment by sjackman** [comment]
Could someone please report the output of…
```sh
ls -ld ~/.linuxbrew/Cellar ~/.linuxbrew/Homebrew ~/.cache/Homebrew
```
The permissions of these directories should be `0755` or `drwxr-xr-x`

**Comment by vangorden** [comment]
This is from my WSL environment, I'm experiencing this issue as well.
```
$ ls -ld /home/linuxbrew/.linuxbrew/Cellar /home/linuxbrew/.linuxbrew/Homebrew ~/.cache
drwxrwxr-x 1 nvg  nvg  4096 Oct 31 12:57 /home/linuxbrew/.linuxbrew/Cellar
drwxrwxrwx 1 nvg  nvg  4096 Oct 24 21:09 /home/linuxbrew/.linuxbrew/Homebrew
drwxr-xr-x 1 root root 4096 Feb 21  2018 /home/nvg/.cache
```
This patch did not solve the issue for me:

> 
> 
> This patch may work around the issue until a proper fix is found.
> 
> ```diff
> diff --git a/Library/Homebrew/extend/pathname.rb b/Library/Homebrew/extend/pathname.rb
> index 513e11290..6ba55cdf2 100644
> --- a/Library/Homebrew/extend/pathname.rb
> +++ b/Library/Homebrew/extend/pathname.rb
> @@ -166,6 +166,7 @@ class Pathname
>      # for https://github.com/rails/rails/pull/34037.
>      Dir.mktmpdir(".d", dirname) do |tmpdir|
>        should_fix_sticky_bit = dirname.world_writable? && !dirname.sticky?
> +      should_fix_sticky_bit = true
>        FileUtils.chmod "+t", dirname if should_fix_sticky_bit
>        begin
>          File.atomic_write(self, tmpdir) do |file|
> ```
But this one does fix the issue for me:

```diff
diff --git a/Library/Homebrew/extend/pathname.rb b/Library/Homebrew/extend/pathname.rb
index 513e11290..32031c3fe 100644
--- a/Library/Homebrew/extend/pathname.rb
+++ b/Library/Homebrew/extend/pathname.rb
@@ -171,8 +171,6 @@ class Pathname
         File.atomic_write(self, tmpdir) do |file|
           file.write(content)
         end
-      ensure
-        FileUtils.chmod "-t", dirname if should_fix_sticky_bit
       end
     end
   end
```
It seems the sticky bit needs to be reset at a later point in the code, because it is still needed after this method gets called.

**Comment by sjackman** [comment]
> But this one does fix the issue for me:

Thanks for the workaround!

```
$ ls -ld /home/linuxbrew/.linuxbrew/Cellar /home/linuxbrew/.linuxbrew/Homebrew ~/.cache
drwxrwxrwx 1 nvg  nvg  4096 Oct 24 21:09 /home/linuxbrew/.linuxbrew/Homebrew
```

`Homebrew` shouldn't be world-writable. Does the following script resolve the issue?
```sh
find ~/.linuxbrew ~/.cache -type d -exec chmod 0755 {} +
```

**Comment by vangorden** [comment]
> `Homebrew` shouldn't be world-writable. Does the following script resolve the issue?
> 
> ```shell
> find ~/.linuxbrew ~/.cache -type d -exec chmod 0755 {} +
> ```
Unfortunately it does not resolve the issue, but thank you for pointing out, and showing me how to fix my permissions.

**Comment by sjackman** [comment]
Hmm. That's disappointing. This problem should hopefully be fixed by removing the world-writable permissions from whichever directory erroneously has world-writable permissions. I'm just not sure which directory is causing the problem.

**Comment by black-snow** [comment]
```
$ ls -ld ~/.linuxbrew/Cellar ~/.linuxbrew/Homebrew ~/.cache/Homebrew
ls: cannot access '/home/xxx/.linuxbrew/Cellar': No such file or directory
ls: cannot access '/home/xxx/.linuxbrew/Homebrew': No such file or directory
drwxrwxr-t 1 xxx xxx 512 Nov  1 10:40 /home/xxx/.cache/Homebrew
```

There is no `.linuxbrew` in my home - it's inside the linuxbrew's home:
```
$ ls -ld /home/linuxbrew/.linuxbrew/Cellar /home/linuxbrew/.linuxbrew/Homebrew /home/linuxbrew/.cach
e/Homebrew
ls: cannot access '/home/linuxbrew/.cache/Homebrew': No such file or directory
drwxrwxr-x 1 xxx xxx 512 Nov  1 10:16 /home/linuxbrew/.linuxbrew/Cellar
drwxrwxrwx 1 xxx xxx 512 Nov  1 10:12 /home/linuxbrew/.linuxbrew/Homebrew
```

**Comment by sjackman** [comment]
```
drwxrwxrwx 1 xxx xxx 512 Nov  1 10:12 /home/linuxbrew/.linuxbrew/Homebrew
```
Same issue that `~/.linuxbrew/Homebrew` is world writable. Please try…
```sh
ls -ld /home/linuxbrew/.linuxbrew/Cellar /home/linuxbrew/.linuxbrew/Homebrew ~/.cache/Homebrew
find /home/linuxbrew/.linuxbrew ~/.cache -type d -exec chmod 0755 {} +
ls -ld /home/linuxbrew/.linuxbrew/Cellar /home/linuxbrew/.linuxbrew/Homebrew ~/.cache/Homebrew
```

**Comment by rtr-dnd** [comment]
Unfortunately it didn't help in my environment. I also have this issue with installing xorg.

**Comment by sjackman** [comment]
Please report the output of…
```sh
ls -ld /home/linuxbrew/.linuxbrew/Cellar /home/linuxbrew/.linuxbrew/Homebrew ~/.cache/Homebrew
find /home/linuxbrew/.linuxbrew ~/.cache -type d -exec chmod 0755 {} +
ls -ld /home/linuxbrew/.linuxbrew/Cellar /home/linuxbrew/.linuxbrew/Homebrew ~/.cache/Homebrew
```
I don't have access to WSL to try it myself.

**Comment by vangorden** [comment]
I think I may have found the root of the issue with WSL. It appears the umask is set to 0000 depending on how you login to your shell, causing all new directories to get world writable permissions. There is an issue report here: https://github.com/Microsoft/WSL/issues/352. The simplest fix is to add `umask 022` to your .profile or to login with `sudo /bin/login`. I have confirmed that either of these options resolves the issue on my machine.

**Comment by sjackman** [comment]
Woohoo! Thanks for the fix, Noah!

`brew doctor` should check and report an issue when `umask` is `000`. I'd happily accept a PR if anyone has the time and inclination to submit one.
