### ISSUE TITLE
Error: undefined method `rebuild' for #<BottleSpecification:0x7f0c69ca2430>

### ISSUE THREAD

**Issue by xDigital** [Linuxbrew/brew#878]
```
*Please report this bug:
    https://github.com/Linuxbrew/linuxbrew/blob/master/share/doc/homebrew/Troubleshooting.md#troubleshooting
/home/fzutljptf41p/.linuxbrew/Library/Taps/homebrew/homebrew-core/Formula/ta-lib.rb:9:in `load_formula'
/home/fzutljptf41p/.linuxbrew/Library/Homebrew/software_spec.rb:91:in `instance_eval'
/home/fzutljptf41p/.linuxbrew/Library/Homebrew/software_spec.rb:91:in `bottle'
/home/fzutljptf41p/.linuxbrew/Library/Homebrew/formula.rb:1729:in `bottle'
/home/fzutljptf41p/.linuxbrew/Library/Taps/homebrew/homebrew-core/Formula/ta-lib.rb:7:in `load_formula'
/home/fzutljptf41p/.linuxbrew/Library/Homebrew/formulary.rb:34:in `load_formula_from_path'
/home/fzutljptf41p/.linuxbrew/Library/Homebrew/formulary.rb:83:in `load_file'
/home/fzutljptf41p/.linuxbrew/Library/Homebrew/formulary.rb:74:in `klass'
/home/fzutljptf41p/.linuxbrew/Library/Homebrew/formulary.rb:70:in `get_formula'
/home/fzutljptf41p/.linuxbrew/Library/Homebrew/formulary.rb:207:in `factory'
/home/fzutljptf41p/.linuxbrew/Library/Homebrew/extend/ARGV.rb:18:in `formulae'
/home/fzutljptf41p/.linuxbrew/Library/Homebrew/extend/ARGV.rb:16:in `map'
/home/fzutljptf41p/.linuxbrew/Library/Homebrew/extend/ARGV.rb:16:in `formulae'
/home/fzutljptf41p/.linuxbrew/Library/Homebrew/cmd/install.rb:44:in `install'
/home/fzutljptf41p/.linuxbrew/Library/brew.rb:84:in `send'
/home/fzutljptf41p/.linuxbrew/Library/brew.rb:84
```

**Comment by sjackman** [comment]
Please surround copied-and-pasted logs with triple back ticks. See [GitHub Help / Quoting Code](https://help.github.com/articles/basic-writing-and-formatting-syntax/#quoting-code).

**Comment by sjackman** [comment]
Please fill out the bug report template. It looks as though you have an old installation of Linuxbrew. Try `brew update` or if that doesn't resolve the issue `brew update-reset`.
