### ISSUE TITLE
bzip2: Syntax error: Unterminated quoted string [Windows]

### ISSUE THREAD

**Issue by JMoVS** [Linuxbrew/brew#95]
# Please follow the general troubleshooting steps first:
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [x] If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`?
### Bug reports:

Trying to install mkvtoolnix results in an error of the tar command.

To be exact, the result is:

```
justin@myPC:/mnt/c/Users/scholju$ brew install -v mkvtoolnix
/home/justin/.linuxbrew/Library/Homebrew/utils/analytics.sh: Zeile 41: /proc/sys/kernel/random/uuid: Datei oder Verzeichnis nicht gefunden
==> Installing dependencies for mkvtoolnix: boost, libebml, libmatroska
==> Installing mkvtoolnix dependency: boost
==> Downloading https://downloads.sourceforge.net/project/boost/boost/1.61.0/boost_1_61_0.tar.bz2
Already downloaded: /home/justin/.cache/Homebrew/boost-1.61.0.tar.bz2
==> Verifying boost-1.61.0.tar.bz2 checksum
tar xvjf /home/justin/.cache/Homebrew/boost-1.61.0.tar.bz2
/home/justin/.linuxbrew/bin/bzip2: 2: /home/justin/.linuxbrew/bin/bzip2: Syntax error: Unterminated quoted string
tar: Child returned status 2
tar: Error is not recoverable: exiting now
Error: Failure while executing: tar xvjf /home/justin/.cache/Homebrew/boost-1.61.0.tar.bz2

```

**Comment by sjackman** [comment]
I'm afraid that I don't have a Windows system on which to test. Sorry. I would like to get Linuxbrew running on Windows Subsystem for Linux, but a developer that regularly uses Windows would need to volunteer to maintain it.

**Comment by JMoVS** [comment]
I was wondering whether that is a bug with the package or with a too-long path or something like that. Can I turn on even more verbosity to look more into it?

**Comment by bw-yuhogg** [comment]
You might want to try `-vd` instead of just `-v`. That lets you open a shell or see a Ruby backtrace (among other things) when it fails.

**Comment by JMoVS** [comment]
it seems like the tar command is partially broken due to missing full symlink support - https://wpdev.uservoice.com/forums/266908-command-prompt-console-bash-on-ubuntu-on-windo/suggestions/13254597-support-for-symlinks-and-long-filenames-in-bash

so it's not a linuxbrew bug it seems

**Comment by JMoVS** [comment]
I can try running it with -vd and try untaring on a VolFS folder and see if that works and cp it back

**Comment by JMoVS** [comment]
ok. The error I've seen stems from the bottled bzip2 from linuxbrew. When I use the bundled bzip2 or build it from source itself, it works flawlessly.

**Comment by JMoVS** [comment]
sorry, didn't want to overwrite your title change -.-

**Comment by sjackman** [comment]
No worries. We like to start the subject line with `package:`

**Comment by JMoVS** [comment]
should I migrate the issue to linuxbrew/core as this is really more a package issue?

**Comment by sjackman** [comment]
Not just yet. I'd like to know whether this issue affects more than just the `bzip2` bottle. I suspect it would.

**Comment by ilovezfs** [comment]
I'm surprised this works at all already. Fun.

**Comment by sjackman** [comment]
@JMoVS Does `brew install hello` work?

**Comment by JMoVS** [comment]
well, `brew install hello` works, but it also doesn't seem to be a bz2 file, whereas in the case of boost, it is

**Comment by sjackman** [comment]
That's better than I had hoped. Cool!

**Comment by sjackman** [comment]
Can you install `bzip2` from a bottle and report the output of `brew test bzip2`
Then do the same after install `bzip2` from source?

**Comment by JMoVS** [comment]
```
Testing bzip2
==> /home/justin/.linuxbrew/Cellar/bzip2/1.0.6_1/bin/bzip2 /tmp/bzip2-test-20160812-12335-2qgura/sample_in.txt
Last 15 lines from /home/justin/.cache/Homebrew/Logs/bzip2/01.bzip2:
2016-08-12 20:18:11 +0200

/home/justin/.linuxbrew/Cellar/bzip2/1.0.6_1/bin/bzip2
/tmp/bzip2-test-20160812-12335-2qgura/sample_in.txt

/home/justin/.linuxbrew/Cellar/bzip2/1.0.6_1/bin/bzip2: 2: /home/justin/.linuxbrew/Cellar/bzip2/1.0.6_1/bin/bzip2: Syntax error: Unterminated quoted string
Error: bzip2: failed
Failed executing: /home/justin/.linuxbrew/Cellar/bzip2/1.0.6_1/bin/bzip2 /tmp/bzip2-test-20160812-12335-2qgura/sample_in.txt
/home/justin/.linuxbrew/Library/Homebrew/formula.rb:1508:in `block in system'
/home/justin/.linuxbrew/Library/Homebrew/formula.rb:1445:in `open'
/home/justin/.linuxbrew/Library/Homebrew/formula.rb:1445:in `system'
/home/justin/.linuxbrew/Library/Taps/homebrew/homebrew-core/Formula/bzip2.rb:40:in `block in <class:Bzip2>'
/home/justin/.linuxbrew/Library/Homebrew/formula.rb:1350:in `block in run_test'
/home/justin/.linuxbrew/Library/Homebrew/extend/fileutils.rb:14:in `block in mktemp'
/home/justin/.linuxbrew/Library/Homebrew/extend/fileutils.rb:75:in `block in run'
/home/justin/.linuxbrew/Library/Homebrew/extend/fileutils.rb:75:in `chdir'
/home/justin/.linuxbrew/Library/Homebrew/extend/fileutils.rb:75:in `run'
/home/justin/.linuxbrew/Library/Homebrew/extend/fileutils.rb:13:in `mktemp'
/home/justin/.linuxbrew/Library/Homebrew/formula.rb:1344:in `run_test'
/home/justin/.linuxbrew/Library/Homebrew/test.rb:33:in `block in <main>'
/usr/lib/ruby/1.9.1/timeout.rb:69:in `timeout'
/home/justin/.linuxbrew/Library/Homebrew/test.rb:32:in `<main>'
```

**Comment by sjackman** [comment]
What's in this file? `/home/justin/.linuxbrew/Cellar/bzip2/1.0.6_1/bin/bzip2`
Please report:

```
ls -l /home/justin/.linuxbrew/Cellar/bzip2/1.0.6_1/bin/bzip2
file /home/justin/.linuxbrew/Cellar/bzip2/1.0.6_1/bin/bzip2
```

**Comment by JMoVS** [comment]
opened the bzip2 thingy with sublime but had no luck. neither with nano.

**Comment by sjackman** [comment]
Can you please run the above two lines of shell code at the prompt?

**Comment by JMoVS** [comment]
```
-r-xr-xr-x 1 justin justin 306284 Aug 12 20:41 /home/justin/.linuxbrew/Cellar/bzip2/1.0.6_1/bin/bzip2
/home/justin/.linuxbrew/Cellar/bzip2/1.0.6_1/bin/bzip2: ELF 64-bit LSB  executable, x86-64, version 1 (SYSV), dynamically linked (uses shared libs), for GNU/Linux 2.6.24, BuildID[sha1]=7ef1ceb2b6e289ec4ee09cce1ee0622ce561ddab, not stripped
```

do you want me to do the same for the working self compiled version?

Sry, just now seen the task to do self compile and test. Will do now

**Comment by JMoVS** [comment]
testing output from the self-built working version:

```
Testing bzip2
==> /home/justin/.linuxbrew/Cellar/bzip2/1.0.6_1/bin/bzip2 /tmp/bzip2-test-20160812-14667-xvpyq6/sample_in.txt
==> /home/justin/.linuxbrew/Cellar/bzip2/1.0.6_1/bin/bunzip2 /tmp/bzip2-test-20160812-14667-xvpyq6/sample_in.txt.bz2
```

and the ls as well as the file:

```
-r-xr-xr-x 1 justin justin 293964 Aug 12 20:53 /home/justin/.linuxbrew/Cellar/bzip2/1.0.6_1/bin/bzip2
/home/justin/.linuxbrew/Cellar/bzip2/1.0.6_1/bin/bzip2: ELF 64-bit LSB  executable, x86-64, version 1 (SYSV), dynamically linked (uses shared libs), for GNU/Linux 2.6.24, BuildID[sha1]=83d2321e0944ec5e4ab2bdedf54b23e63bb623f6, not stripped
```

**Comment by sjackman** [comment]
One hypothesis I have is that the Windows kernel is not able to load some (but it seems not all) executables that have been fixed up by `patchelf`. Can you reconfirm that the following works?

``` sh
brew install hello
brew test hello
hello
```

Please report the results of the following test:

``` sh
brew install bzip2
brew test bzip2
brew reinstall -s bzip2
brew test bzip2
brew patchelf bzip2
brew test bzip2
```

**Comment by JMoVS** [comment]
brew install bzip2 (bottled) is as above,

brew install bzip2 from source works fine

the moment I ran patchelf, output is again:

```
Testing bzip2
==> /home/justin/.linuxbrew/Cellar/bzip2/1.0.6_1/bin/bzip2 /tmp/bzip2-test-20160815-14643-nxm07j/sample_in.txt
/home/justin/.linuxbrew/Cellar/bzip2/1.0.6_1/bin/bzip2: 1: /home/justin/.linuxbrew/Cellar/bzip2/1.0.6_1/bin/bzip2: ELF: not found
/home/justin/.linuxbrew/Cellar/bzip2/1.0.6_1/bin/bzip2: 2: /home/justin/.linuxbrew/Cellar/bzip2/1.0.6_1/bin/bzip2: Syntax error: Unterminated quoted string
Error: bzip2: failed
Failed executing: /home/justin/.linuxbrew/Cellar/bzip2/1.0.6_1/bin/bzip2 /tmp/bzip2-test-20160815-14643-nxm07j/sample_in.txt
/home/justin/.linuxbrew/Library/Homebrew/formula.rb:1508:in `block in system'
/home/justin/.linuxbrew/Library/Homebrew/formula.rb:1445:in `open'
/home/justin/.linuxbrew/Library/Homebrew/formula.rb:1445:in `system'
/home/justin/.linuxbrew/Library/Taps/homebrew/homebrew-core/Formula/bzip2.rb:40:in `block in <class:Bzip2>'
/home/justin/.linuxbrew/Library/Homebrew/formula.rb:1350:in `block in run_test'
/home/justin/.linuxbrew/Library/Homebrew/extend/fileutils.rb:14:in `block in mktemp'
/home/justin/.linuxbrew/Library/Homebrew/extend/fileutils.rb:75:in `block in run'
/home/justin/.linuxbrew/Library/Homebrew/extend/fileutils.rb:75:in `chdir'
/home/justin/.linuxbrew/Library/Homebrew/extend/fileutils.rb:75:in `run'
/home/justin/.linuxbrew/Library/Homebrew/extend/fileutils.rb:13:in `mktemp'
/home/justin/.linuxbrew/Library/Homebrew/formula.rb:1344:in `run_test'
/home/justin/.linuxbrew/Library/Homebrew/test.rb:33:in `block in <main>'
/usr/lib/ruby/1.9.1/timeout.rb:69:in `timeout'
/home/justin/.linuxbrew/Library/Homebrew/test.rb:32:in `<main>'
```

**Comment by sjackman** [comment]
That test confirms that the Windows kernel is not able to load executables that have been modified by `patchelf`. =/ The workaround is to set

```
export HOMEBREW_BUILD_FROM_SOURCE=1
```

**Comment by sjackman** [comment]
I believe that this issue has been resolved by the upstream Windows developers.

**Comment by JMoVS** [comment]
Might be the case, but unfortunately, I no longer have the means to test this. :-/
